### ISSUE TITLE
Threading with neo4j-jdbc driver on Google Dataflow

### ISSUE THREAD

**Issue by sx5640** [neo4j/neo4j-jdbc#102]
I'm running setup where I'm hosting a Neo4j database on a Google Compute Engine, and writing to the database using Google Dataflow, through jdbcIO API with Neo4j-jdbc driver. With Dataflow doing threading automatically, I'm running in to a deadlock issue when multiple threads try to hit the same node around the same time. 

I'm trying to debug this issue, and my question is: is neo4j-jdbc driver thread-safe? (e.g., is it creating a thread-safe driver object each time similar to the neo4j-java-driver)

The error message looks like this:
```
Exception: java.sql.BatchUpdateException: org.neo4j.driver.v1.exceptions.TransientException: LockClient[474] can't wait on resource RWLock[NODE(234), hash=323832533] since => LockClient[474] <-[:HELD_BY]- RWLock[NODE(263), hash=2077243017] <-[:WAITING_FOR]- LockClient[477] <-[:HELD_BY]- RWLock[NODE(234), hash=323832533]
org.neo4j.jdbc.bolt.BoltPreparedStatement.executeBatch(BoltPreparedStatement.java:178)
org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345)
org.apache.commons.dbcp2.DelegatingStatement.executeBatch(DelegatingStatement.java:345)
org.apache.beam.sdk.io.jdbc.JdbcIO$Write$WriteFn.finishBundle(JdbcIO.java:480)
Caused By: org.neo4j.driver.v1.exceptions.TransientException: LockClient[474] can't wait on resource RWLock[NODE(234), hash=323832533] since => LockClient[474] <-[:HELD_BY]- RWLock[NODE(263), hash=2077243017] <-[:WAITING_FOR]- LockClient[477] <-[:HELD_BY]- RWLock[NODE(234), hash=323832533]
org.neo4j.driver.internal.connector.socket.SocketResponseHandler.handleFailureMessage(SocketResponseHandler.java:71)
org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.unpackFailureMessage(PackStreamMessageFormatV1.java:464)
org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:425)
org.neo4j.driver.internal.connector.socket.SocketClient.receiveOne(SocketClient.java:130)
org.neo4j.driver.internal.connector.socket.SocketConnection.receiveOne(SocketConnection.java:143)
```

And my implementation looks like this:
```
apply(JdbcIO.<Event>write()
  .withDataSourceConfiguration(JdbcIO.DataSourceConfiguration
      create("org.neo4j.jdbc.Driver", "jdbc:neo4j:bolt://localhost:7687")								
      .withUsername(options.getUsername()).withPassword(options.getPassword()))
  .withStatement(query)
  .withPreparedStatementSetter(new JdbcIO.PreparedStatementSetter<Event>() {
      public void setParameters(Event event, PreparedStatement query) throws SQLException {
           query.setString(1, event.getUser().getId());
...
```

**Comment by glaggia-larus** [comment]
If you are using the BOLT protocol what we did was to wrap the actual neo4j-java-driver so if the driver itself is thread-safe we can assume that the driver could be so.

**Comment by albertodelazzari** [comment]
@sx5640 You're trying to write/update a node concurrently and if there is an existing open (write) transaction you can't do this. When the first thread writes/updates the node it locks the node (if it is not already locked) and it will be locked until the transaction completes. If another thread tries to write/update the same node while it is locked then you will get a TransientException. In this case you can catch the exception and retry the write/update operation.

**Comment by fbiville** [comment]
Closing this as we have not heard back.
