### ISSUE TITLE
Test with Knime

### ISSUE THREAD

**Issue by luto65** [neo4j/neo4j-jdbc#103]
Knime.org is a well known platform that facilitate ETL processes through UI.
Using JDBC drivers version 2.3.2 has been reported as viable approach for "select" statements.
However no example has been provided on "inserts" and "bulk inserts" from KNIME.

**Comment by jexp** [comment]
@luto65 would you be able to help us with the testing? Not sure if Knime has free trial instances and we might have have no experience with it.

**Comment by ch-ricardor** [comment]
Hello, 
I did a test with KNIME and Neo4j using the connector.

I downloaded the jar file: https://neo4j.com/blog/neo4j-jdbc-driver-3-0-3-and-3-1-0-released/ in the section "Start Using the JDBC Driver for Neo4j in 5 Minutes" to be installed in KNIME.

In KNIME:

File->Preferences->KNIME->Databases

Add File
Browse the directory where you downloaded or installed the .jar file.

With this procedure the connector will be available in the Node: Database->Connector->J Database Connector

![image](https://user-images.githubusercontent.com/22514626/48278653-6f425400-e44e-11e8-98d5-6d35d8f2da2a.png)

Configure the connector with your specific requirements, url and credentials.
![image](https://user-images.githubusercontent.com/22514626/48278791-d19b5480-e44e-11e8-8fcd-c877e191259e.png)

Include the cypher query in the "SQL Statement" section.

![image](https://user-images.githubusercontent.com/22514626/48278866-0c04f180-e44f-11e8-8ab3-718931391f38.png)

Transformed to JSON

![image](https://user-images.githubusercontent.com/22514626/48278939-55554100-e44f-11e8-875d-43d9c28daca9.png)

Now I'm trying to recreate the Neo4j image of the graph in KNIME:

![image](https://user-images.githubusercontent.com/22514626/48279005-8df51a80-e44f-11e8-849a-f0f273129ae8.png)

## NOTE:
I executed: Merge (toCont001:World { name:"World", ISOCode:"001"}) **return toCont001**
in a "**Database Reader**" Node. 
The "return" in the cypher is needed to avoid Knime error "ERROR Database Reader      2:6        Execute failed: java.lang.NullPointerException".

![image](https://user-images.githubusercontent.com/22514626/48279501-13c59580-e451-11e8-9b6d-8bed6f1d0a33.png)

**Comment by jexp** [comment]
@ch-ricardor sorry for the late reply, this is really awesome,
would you be able to add your issue comment to our docs on testing the connector with different tools in a PR?

see here: https://github.com/neo4j-contrib/neo4j-jdbc/tree/3.4/docs

**Comment by michael-simons** [comment]
Works with version 6.
