### ISSUE TITLE
Eclipse BIRT tools: use parameters in query

### ISSUE THREAD

**Issue by b3no3** [neo4j/neo4j-jdbc#106]
I created a data set with a parameter called "par_id" (Integer, default value: 1) and the following query:

MATCH (a:A) WHERE a.id = ?
RETURN a.type

As soon as clicking on any property of the data set (e.g. Preview Results) an error dialog is shown with the following message: 

"Expected a parameter named 1"

My connection string: "jdbc:neo4j:bolt://localhost?flatten=1"

It works perfectly when running the query without a parameter.  

When I try to use the HTTP driver an error occurs "Index: 0, Size: 0" 

I does work with SQL queries / databases.

EDIT: The error occurs because the parameter marker is replaced by curly places, which include the actual parameter value. Without these it would work. Is there a way to disable this behaviour?

**Comment by jexp** [comment]
Not really sure what birt does there. Does it replace the ? itself? Or is there another syntax in birt where it replaces parameters with values?

You add a ? to your query, which is then replaced by the JDBC driver by {1} b/c it's the first parameter.
(and JDBC only allows numeric parameters).

**Comment by b3no3** [comment]
It replaces the first ? with the first defined parameter, the second with the second defined parameter and so on.  Just did a test again you're right, I thought the ? is replaced by the default value of the parameter, but it is the number of the parameter (1 for the first, 2 for the second...).

It does not replace the ? with the defined default value of the parameter like when using SQL. My solution right now is to get all data and then filter it. It seems all non-relational data sources have this behaviour as discussed here:
https://stackoverflow.com/questions/11719425/how-to-pass-parameters-to-data-set-behind-a-data-cube-in-birt

I don't know how birt does replace the ? in the background. I'm quite a beginner in birt.

**Comment by jexp** [comment]
@glaggia-larus did we resolve this issue?

**Comment by glaggia-larus** [comment]
Not that I know. This is still in the backlog

**Comment by michael-simons** [comment]
This works just fine in version 6

![image](https://github.com/neo4j/neo4j-jdbc/assets/526383/9c9d5b68-5d18-4d03-935e-41c57b305f03)

![image](https://github.com/neo4j/neo4j-jdbc/assets/526383/cefed48b-74ee-4eba-8d31-884216ec9f1f)
