### ISSUE TITLE
neo4j-jdbc-mybatis

### ISSUE THREAD

**Issue by wuyu8995861** [neo4j/neo4j-jdbc#107]
org/neo4j/jdbc/example/mybatis/mapper/ActorMapper.xml is here?

**Comment by inserpio** [comment]
Hi @wuyu8995861, honestly I can't understand what you're asking for, but if you're looking for the file, then it's located here: neo4j-jdbc-examples/mybatis/src/main/resources/org/neo4j/jdbc/example/mybatis/mapper

**Comment by wuyu8995861** [comment]
thanks i find is that
 ..examples/mybatis/src/main/resources/org/neo4j/jdbc/example/mybatis/mapper/ActorMapper.xml

**Comment by inserpio** [comment]
cool, so I'll close the issue, ok?

**Comment by wuyu8995861** [comment]
this  is support  ibatis ？

**Comment by albertodelazzari** [comment]
@wuyu8995861 mybatis is a fork project from ibatis (I think 3.0 version) so even if the example is for mybatis I think it should work even for ibatis

**Comment by albertodelazzari** [comment]
Can we close this issue?
