### ISSUE TITLE
Integer - Long type mismatch between Bolt and Http protocols

### ISSUE THREAD

**Issue by dadrus** [neo4j/neo4j-jdbc#108]
According to [Neo4j Type Mapping for Java](https://neo4j.com/docs/developer-manual/current/drivers/cypher-values/#driver-type-mappings), the Neo4j Integer type is represented as `java.lang.Long`. This representation is given by the Bolt protocol, but unfortunately not by the Http protocol implementation of the jdbc driver. All integral number, which can fit into 32 bits are represented as `java.lang.Integer`. The implementation of the Http protocol uses jackson internally for data type conversion purposes, which by default implements the behavior, described above (see e.g also this [Stackoverflow article](https://stackoverflow.com/questions/7316689/forcing-jackson-to-deserialize-to-specific-primitive-type)). The solution of this issue would be, as also described in the referenced article, to configure jackson's `ObjectMapper` with `DeserializationFeature.USE_LONG_FOR_INTS`.

**Comment by inserpio** [comment]
Hi @dadrus, we can patch it and send you a snapshot, until we don't create a new release if that's ok for you.
You're right, we updated the bolt one first and not yet done with the http part

**Comment by dadrus** [comment]
Hi @inserpio. Thank you very much for the offer. In my case it is however not urgent at all. I'm working on [jpa-unit](https://github.com/dadrus/jpa-unit), a test framework, which targets JPA specific tests for RDBMS, as well as for NoSQL DBs and ran into this issue during the implementation of the corresponding extension for Neo4j. So I can easily wait for the official release.
