### ISSUE TITLE
Issue while connecting NEO4J to JASPERSOFT 

### ISSUE THREAD

**Issue by jyothi1121** [neo4j/neo4j-jdbc#109]
I am trying to connect NEO4J to JASPER SOFT. I referred below link for connection process.
http://neo4j-contrib.github.io/neo4j-jdbc/#_jdbc_compatibility
STEP 1 "Creating new Data Adapters" is successful and Database is successfully connected to JDBC.

But in STEP 2 "Retrieve Columns from Database" , i am facing an issue while fetching data from NEO4J database which is a part of creating JASPER report.
I am getting an error like "GETTING METADATA FOR NEO4J.....PLEASE WAIT...".
I am not sure whether this issue is regarding driver problem or URL problem.
Please provide me a solution for this.

**Comment by inserpio** [comment]
Hi, I'm afraid something's missing on the metadata side. We're currently working on it.
As you can find in the guide, there's a working example of how to use the driver with Jasper.
Which version of Jasper are you using?

**Comment by jyothi1121** [comment]
I followed exactly the same steps as mentioned in the working example after which i am getting the above issue. Currently, I am using Jaspersoft studio version 6.4.0

**Comment by inserpio** [comment]
Let me double check it

**Comment by jexp** [comment]
@inserpio did you check this?

**Comment by omarlarus** [comment]
It'll be fixed with the [PR 166](https://github.com/neo4j-contrib/neo4j-jdbc/pull/166)
