### ISSUE TITLE
Invalid input '{': expected whitespace or a label name

### ISSUE THREAD

**Issue by xho22** [neo4j/neo4j-jdbc#110]
How to set label in create node cql?
`String query = "CREATE (n:{1} {})";`
`try (PreparedStatement stmt = con.prepareStatement(query)) {`
       ` stmt.setString(1,"testLabel");`
`stmt.executeUpdate();`
        `  }}`

I test "CREATE (n:{1} {})" and CREATE (n:? {}), both of them are all error.

**Comment by inserpio** [comment]
You can't pass the label name as a parameter. It's a cypher limit, not a jdbc one, but you can easy solve that by calling a specific APOC.
