### ISSUE TITLE
ResultSet.getObject(int, class) throws java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by miteshaghera** [neo4j/neo4j-jdbc#112]
`resultSet.getObject(1, Map.class);` throws `Method threw 'java.lang.UnsupportedOperationException' exception.`

**Comment by jexp** [comment]
Do you have any JDBC drivers that support that?
We could do it when your cypher returns a map.

what happens if you just call rs.getObject(1) ?

**Comment by miteshaghera** [comment]
@jexp Normally rdbms drivers support this.

When I call rs.getObject(1), it returns HashMap however I need cast explicitly.

**Comment by jexp** [comment]
I was not aware of trad. rdbms supporting maps. 

We can fix this.
What is the expected failure behavior if the element is not a map?
Fail or construct a single element map?

**Comment by miteshaghera** [comment]
I'm not sure fail vs single element however I personally prefer single element map over the failure.

Please refer [java doc](https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html#getObject(java.lang.String,%20java.lang.Class))
