### ISSUE TITLE
Test with Qlikview

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#12]

**Comment by jexp** [comment]
@ralfbecher want to add your findings?

**Comment by ralfbecher** [comment]
Works with TIQ Solutions' JDBC Connector

**Comment by inserpio** [comment]
Adding picture to be referenced in the "Neo4j JDBC Driver Documentation"

![qlik config](https://cloud.githubusercontent.com/assets/6613815/17213244/d04d482a-54d3-11e6-8813-29d3d701ea2b.png)
![qlik results](https://cloud.githubusercontent.com/assets/6613815/17213245/d04dbd14-54d3-11e6-914e-0729e02e61e9.png)
![qlik settings](https://cloud.githubusercontent.com/assets/6613815/17213246/d04dfe14-54d3-11e6-98bf-3a58bb3344a8.png)
![qlik results 2](https://cloud.githubusercontent.com/assets/6613815/17213472/add61f14-54d4-11e6-8ed6-3792786c45c3.png)
