### ISSUE TITLE
Regression in exception handling

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#124]
When we upgraded Liquigraph to `3.0.1` to `3.1.0`, some tests were failing because of the way the exception handling has changed:

```java
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery("toto")) { //<-- invalid Cypher
            // do something
        }
        catch (SQLException e) {
            // do something
        }
```

The above snippet used to work. However, in `3.1.0`, a `ClientException` is thrown instead, which leaks from the underlying Bolt driver.

Could it be possible to wrap this error again?

**Comment by glaggia-larus** [comment]
I can't reproduce the issue, not in 3.2 nor in 3.1.

In both branches this test:

```java
@Test
	public void issue124 () throws SQLException {
		Connection connection = DriverManager.getConnection(NEO4J_JDBC_BOLT_URL);
		final Statement statement = connection.createStatement();
		statement.executeQuery("wrong");
	}
```

throws a SQLException as requested.

Can you give me more info on how you are getting this problem?

**Comment by fbiville** [comment]
The change in error handling was done [here](https://github.com/liquigraph/liquigraph/commit/3175aee86c3710db5f2d207f4bcac070196fb956).

As far as I remember, this [test](https://github.com/liquigraph/liquigraph/blob/86264dde7cdd3ad2eb89ba7f4f0826958833e516/liquigraph-core/src/test/java/org/liquigraph/core/io/ConditionExecutorTestSuite.java#L111) was failing.

Neo4j JDBC driver version is updated [here](https://github.com/liquigraph/liquigraph/commit/3175aee86c3710db5f2d207f4bcac070196fb956#diff-600376dffeb79835ede4a0b285078036R34).

Have you tried running the test against the tag `3.1.0`?
Have there been stable releases since if it is fixed by later commits?

**Comment by glaggia-larus** [comment]
I tried the test since the release tag 3.1.0 that is the commit of the actual release.

Can you try to build a jar of the actual 3.2 branch (or I can build it for you) and use that?

**Comment by fbiville** [comment]
Let me try that tomorrow morning. :)

**Comment by jexp** [comment]
@fbiville did you try it?

**Comment by jexp** [comment]
@fbiville ping?

**Comment by fbiville** [comment]
I'll try to test it today.
Else feel free to close it, I'll reopen it when I find time.
