### ISSUE TITLE
A little confusion about execute and executeUpdate return value

### ISSUE THREAD

**Issue by Jacob-Zhou** [neo4j/neo4j-jdbc#132]
When I tried using MATCH-SET to change the property of node with preparedStatement.executeUpdate() or preparedStatement.execute(). the return value is not expected that the return value alway is 0 or false no matter whether the result is a failure or a success.

**Comment by inserpio** [comment]
MATCH-SET without RETURN?

**Comment by inserpio** [comment]
If you don't return anything than it's correct that execute returns false as you have no resultset.
ExecuteUpdate returns zero are we are just counting nodes / rels but we ignore properties (nodesCreated + nodesDeleted + relationshipsCreated + relationshipsDeleted).

**Comment by Jacob-Zhou** [comment]
thx~
