### ISSUE TITLE
No suitable driver found for jdbc:neo4j:/localhost:7474

### ISSUE THREAD

**Issue by neo4j-dk** [neo4j/neo4j-jdbc#133]
i have the following code to test connection to the neo4j: version 2.2.5
i am using driver of: neo4j-jdbc-driver-3.3.0.jar
i already defined the $CLASSPATH so that to include neo4j-jdbc-driver-3.3.0.jar but i got 
'No suitable driver found for jdbc:neo4j:/localhost:7474'

Could anyone help with this?
Thanks,

java Neo4jConnectionTest1
---1---
---1-1---
---3---No suitable driver found for jdbc:neo4j:/localhost:7474

more Neo4jConnectionTest1.java

import org.neo4j.jdbc.*;
import java.sql.DriverManager;
import java.sql.*;

public class Neo4jConnectionTest1 {
    public static void main(String[] args) {
    try {
        Class.forName("org.neo4j.jdbc.Driver");
        System.out.println("---1---");

        // connect
        System.out.println("---1-1---");
        Neo4jConnection con = (Neo4jConnection)DriverManager.getConnection("jdbc:neo4j:/localhost:7474", "neo4j", "neo4j")
;
        System.out.println("---2---");

        // Querying
        String query = "MATCH (u:User)-[:FRIEND]-(f:User) WHERE u.name = {1} RETURN f.name, f.age";
        try {
            PreparedStatement stmt = (PreparedStatement)con.prepareStatement(query);
            stmt.setString(1,"John");

            try {
                ResultSet rs = (ResultSet)stmt.executeQuery();
                while (rs.next()) {
                    System.out.println("Friend: "+rs.getString("f.name")+" is "+rs.getInt("f.age"));
                }
		} catch (Exception e1) {System.out.println("---1---" + e1.getMessage());}
	    } catch (Exception e2) {System.out.println("---2---" + e2.getMessage());}
	} catch (Exception e3) {System.out.println("---3---" + e3.getMessage());}
    }
}

**Comment by jexp** [comment]
It misses one slash. 
`jdbc:neo4j://localhost:7474`

and better to use bolt `jdbc:neo4j:bolt://localhost`

also you cannot use the default password

**Comment by neo4j-dk** [comment]
just modified with extra slash and using jdbc:neo4j:bolt//localhost without password,
still received the same error:
No suitable driver found for '....'

Thanks!

**Comment by inserpio** [comment]
Are you using it in some kind of container? Or pure java?

**Comment by neo4j-dk** [comment]
using Java 1.8: just want to create a sample test code to connect to the neo4j db.
Thanks!

**Comment by inserpio** [comment]
something like: `java -cp neo4j-jdbc-driver-3.3.0.jar Neo4jConnectionTest1 ` ?

**Comment by neo4j-dk** [comment]
tried that already!
it found the jar file otherwise the code
Class.forName("org.neo4j.jdbc.Driver"); 
won't work which is before the System.out.println("---1---");

Thanks!

**Comment by inserpio** [comment]
it's not necessary to call `Class.forName` <- it auto-discovers the right class to load.
or replace it with `Class.forName("org.neo4j.jdbc.bolt.BoltDriver")`

**Comment by neo4j-dk** [comment]
modified and compiled but still failed for the same error:
No suitable driver found for jdbc:neo4j:....

Thanks!

**Comment by inserpio** [comment]
weird! any change to share the test project?

**Comment by neo4j-dk** [comment]
the code i posted just a standalone java class: even the back-end (neo4j) is not running, i will expect some other kind of errors but not this one, right?

Thanks!

**Comment by neo4j-dk** [comment]
just fixed the connection issue by adding ':bolt' into getConnection(...)

Neo4jConnection con = (Neo4jConnection)DriverManager.getConnection("jdbc:neo4j:bolt://localhost:7474");

will try the connection but failed due to the unrecognized SSL message, plaintext connection issue.

Thank you all.

**Comment by inserpio** [comment]
Just add ?noSsl to the url

**Comment by neo4j-dk** [comment]
yes, just added the ":bolt" and it will try to connect!

**Comment by kaniika31** [comment]
I am using 
CALL apoc.load.jdbc('jdbc:oracle://localhost:1521/oracle?user=sys&password=oracle@123','select * from artists') YIELD row
CREATE (n:artists {name:row.title})

to connect my neo4j database to Oracle database but getting below error 👍 

Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.jdbc`: Caused by: java.sql.SQLException: No suitable driver found for jdbc:oracle://localhost:1521/oracle?user=sys&password=oracle@123

Have set the class path .

**Comment by inserpio** [comment]
Hi @kaniika31, `apoc.load.jdbc` isn't part of this project, but the https://github.com/neo4j-contrib/neo4j-apoc-procedures one. Please refer to it. 
Best,
Lorenzo

**Comment by jexp** [comment]
@kaniika31 please raise the issue in the https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues 

you  most likely forgot to supply the oracle driver jar, please read the docs!!!

**Comment by liukeqing** [comment]
> it's not necessary to call `Class.forName` <- it auto-discovers the right class to load.
> or replace it with `Class.forName("org.neo4j.jdbc.bolt.BoltDriver")`

this works to me,thank you.
