### ISSUE TITLE
org.neo4j.driver.v1.exception.ServiceUnavailableException: unable to process request: unrecognized SSL message, plaintext connectyion?

### ISSUE THREAD

**Issue by neo4j-dk** [neo4j/neo4j-jdbc#134]
i git the following error messages: all i want is for this simple code to make connection with neo4j.
thanks!

---1---
---3---org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Unable to process request: Unrecognized SSL message, plaintext connection?

import org.neo4j.jdbc.*;
import java.sql.DriverManager;
public class Neo4jConnectionTest1 {
    public static void main(String[] args) {
        try {
            Class.forName("org.neo4j.jdbc.bolt.BoltDriver");
            System.out.println("---1---");

            // connect
            Neo4jConnection con = (Neo4jConnection)DriverManager.getConnection("jdbc:neo4j:bolt://localhost:7474", "neo4j", "<password-here>");

            // Querying
            String query = "MATCH (u:User)-[:FRIEND]-(f:User) WHERE u.name = {1} RETURN f.name, f.age";
            try {
                Neo4jPreparedStatement stmt = (Neo4jPreparedStatement)con.prepareStatement(query);
                stmt.setString(1,"John");

                try {
                    Neo4jResultSet rs = (Neo4jResultSet)stmt.executeQuery();
                    while (rs.next()) {
                        System.out.println("Friend: "+rs.getString("f.name")+" is "+rs.getInt("f.age"));
                    }
    	        } catch (Exception e1) {
                    System.out.println("---1---" + e1.getMessage());
                }
            } catch (Exception e2) {
                System.out.println("---2---" + e2.getMessage());
            }
        } catch (Exception e3) {
            System.out.println("---3---" + e3.getMessage());
        }
    }
}

**Comment by inserpio** [comment]
The URL is not correct:
1) Bolt port is 7687 and not 7474
2) add noSsl parameter.

try with `jdbc:neo4j:bolt://localhost?noSsl`

**Comment by neo4j-dk** [comment]
tried but still not working!
i don't know much of neo4j but i don't think neo4j in my environment is setup to run on 7687.
the only reason i am using "jdbc:neo4j:bolt://localhost:7474..." string with 'bolt' in there is to overcome the error of "No suitable driver found for jdbc:neo4j://localhost:7474..." even i have the driver jar file in the CLASSPATH definition.

thanks!

**Comment by neo4j-dk** [comment]
I modified the code so that to create Properties instance and the connection staring is now:
"jdbc:neo4j:http://localhost:7474"
and i am getting the 
Neo.ClientError.Security.AuthorizationFailed]: No Authorization header supplied.
what else i need to set the Properties?
Thanks!

Properties props = new Properties();
props.setProperty("user", "neo4j");
props.setProperty("password", "<password-here>");
props.setProperties("credentials", "<credentials-string-here>");

Neo4jConnection con = (Neo4jConnection)DriverManager.getConnection("jdbc:neo4j:http://localhost:7474", props);

**Comment by glaggia-larus** [comment]
Neo4j is indeed configured to run on port 7687 by default, would you try this address please?

`jdbc:neo4j:bolt://localhost:7687?noSsl`
