### ISSUE TITLE
java.lang.UnsupportedOperationException: Cannot convert from java.lang.String to java.util.List. Requested converter does not exist.

### ISSUE THREAD

**Issue by dangalvinSF** [neo4j/neo4j-jdbc#135]
For the following query:

```
match (start:Table {tableName: 'MD759'}),(end:Table {tableName: 'GRP_PARTY_RLTN'}),
			 p=shortestPath((start)-[r*]-(end)) 
UNWIND nodes(p) as n RETURN n.tableName as tableName,n.columns as columns,n.primaryKeyColumns as primaryKeyColumns,id(n) as id
```
via SpringJdbc:  
`List<SchemaNode> retList = jdbcTemplate.query(NODES_QUERY, start, new BeanPropertyRowMapper<SchemaNode>(SchemaNode.class));`

an attached UnsupportedOperationException was thrown:

```
Caused by: java.lang.UnsupportedOperationException: Cannot convert from java.lang.String to java.util.List. Requested converter does not exist.
	at org.neo4j.jdbc.utils.ObjectConverter.convert(ObjectConverter.java:88)
	at org.neo4j.jdbc.bolt.BoltNeo4jResultSet.getObject(BoltNeo4jResultSet.java:576)
	... 78 common frames omitted
```
Oddly, the exception seems to be eaten and the set for the List<String> succeeds.  

[UnsupportedOperationException.txt](https://github.com/neo4j-contrib/neo4j-jdbc/files/1952564/UnsupportedOperationException.txt)

**Comment by dangalvinSF** [comment]
I am attaching 
[Problem Report Mock Neo4j Graph.txt](https://github.com/neo4j-contrib/neo4j-jdbc/files/2027450/Problem.Report.Mock.Neo4j.Graph.txt)
a sample simple graph to use to recreate the problem.  

Also, I modified the query from this initial report to match the mock graph:
```
match (start:Table {tableName: 'SEGI'}),(end:Table {tableName: 'PARTY}),
			 p=shortestPath((start)-[r*]-(end)) 
UNWIND nodes(p) as n RETURN n.tableName as tableName,n.columns as columns,n.primaryKeyColumns as primaryKeyColumns,id(n) as id
```

**Comment by inserpio** [comment]
Many thanks @dangalvinSF

**Comment by omarlarus** [comment]
Hi @dangalvinSF ! Are you mapping the result into an object with "columns" and "primaryKeyColumns" declared as List?
Looking at the stack trace I'm guessing that the spring framework is trying to convert a String to a List.
I think there's a problem in your model or query. In fact the properties "columns" and "primaryKeyColumns" are setted as String, not array.

To sort out the issue you can use the [split](https://neo4j.com/docs/developer-manual/3.4/cypher/functions/string/#functions-split) function to get a list instead of a string. Here is a an example

```
match (start:Table {tableName: 'SEGI'}),(end:Table {tableName: 'PARTY'}),
p=shortestPath((start)-[r*]-(end))
UNWIND nodes(p) as n
RETURN
n.tableName as tableName,
split(n.columns,',') as columns,
split(n.primaryKeyColumns,',') as primaryKeyColumns,
id(n) as id
```

I suggest you to change your model in this way:
```
columns: ['GRP_ID', 'PARTY_ID', 'VALD_TO_DT', 'RLTN_STRT_DT']
```

Let us know if it solves your problem

**Comment by conker84** [comment]
hi @dangalvinSF any feedback about our suggestion?

**Comment by dangalvinSF** [comment]
Sorry I missed this.  I will try it.  It will take me some time, as I really just gave you a mock.  The real model is substantial.  Thanks for your suggestion!

**Comment by conker84** [comment]
@dangalvinSF I'm closing this, feel free to reopen in case you have new info
