### ISSUE TITLE
NPE in BoltNeo4jResultSet

### ISSUE THREAD

**Issue by bushwakko** [neo4j/neo4j-jdbc#138]
`	private Value fetchValueFromLabel(String label) throws SQLException {
		Value value;
		if (this.current.containsKey(label)) {
			//Requested value is not flattened
			value = this.current.get(label);`

current is apparently null here for me, when doing a CREATE (name:NAME) RETURN name and trying to get the result.

**Comment by omarlarus** [comment]
Hi @bushwakko , the issue is not clear, can you provide any details, please?
We need to know:
- jdbc driver version
- the statement used to execute the create query
- the code after the getResultSet()
- the complete stack trace of the exception

Thanks

**Comment by bushwakko** [comment]
I've since changed my code, so this is not a problem any more. I've refactored quite a bit, so I'm not sure exactly the state of the code when I posted this. I think it might be because I did not do rs.next() possibly.

I apologize for the lack of information in this bug report, very low effort on my part...
