### ISSUE TITLE
enrich getClientInfo map

### ISSUE THREAD

**Issue by inserpio** [neo4j/neo4j-jdbc#149]
It would be good to enrich the client info map with other useful information:

- server address (and port) where the last statement was executed:
- query statistics (nodes updated, nodes deleted, .... etc)

i.e.
```
String server = connection.getClientInfo("execution_server");
String port = connection.getClientInfo("execution_port");
String role = connection.getClientInfo("server_role");  // CORE or READ_REPLICA
int updatedNodes = Integer.parseInt(connection.getClientInfo("nodes_updated"));
```

**Comment by michael-simons** [comment]
The client info properties are about client information, not server ones. Everything mentioned here is server side. We might consider adding client info in the future to v6+ for metrics and related purposes, but we are not gonna use it to carry out this properties towards the client. Thanks for the suggestion, though.
