### ISSUE TITLE
Taking Raw Data

### ISSUE THREAD

**Issue by RaulGF92** [neo4j/neo4j-jdbc#152]
Hi i'm taking queries using java driver and need take the raw statementResult, how i can get that? Thanks you. I will put a piece code like example.

```
try (Connection con = DriverManager.getConnection(urlOfServer, user, password)) {
  try (PreparedStatement stmt = con.prepareStatement("MATCH (n) RETURN n")) {
     try (ResultSet rs = stmt.executeQuery()) {
        //Take here raw data
        return rs;
     }
  }
} 
```

I expect something like this:

``` (json)
[
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 23,
          "high": 0
        },
        "labels": [
          "Node"
        ],
        "properties": {
          "name": "EG - DIRECCION DE CENTRAL COMPRAS BAZAR",
          "identificator": "MODU426"
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  },
  {
    "keys": [
      "n"
    ],
    "length": 1,
    "_fields": [
      {
        "identity": {
          "low": 24,
          "high": 0
        },
        "labels": [
          "Node"
        ],
        "properties": {
          "name": "CIRCUITOS RCM",
          "identificator": "APLI238"
        }
      }
    ],
    "_fieldLookup": {
      "n": 0
    }
  }
]
```

**Comment by jexp** [comment]
Why?
And why don't you the just use the java driver

Please note that there is no json in the java driver at most you get a list of maps

**Comment by RaulGF92** [comment]
Because i need neo4j format for paint a Graph using something like this framework https://github.com/eisman/neo4jd3 , and i can't attack database from client, first need pass by business layer.

**Comment by inserpio** [comment]
Well, this driver is just a pure implementation of the JDBC interface. It doesn’t provide any additional conversion.
Maybe you could rely on some APOC and call them via this driver, or implement you own one, if you can’t do that in the middle tier

**Comment by conker84** [comment]
I'm closing this since this is not a real issue.
