### ISSUE TITLE
Query timing out?

### ISSUE THREAD

**Issue by n1zea144** [neo4j/neo4j-jdbc#153]
I am trying to execute a query which involves a large "IN" clause (~47000 strings in the clause).  If I feed the query to cypher-shell on the command line, it takes a few seconds to complete.  When I programmatically construct the query in a java/jdbc program, a result is never returned from the server and no exceptions are generated.

Could I be encountering some transaction or database connection timeout?  Are there driver properties that I can tweak?  Unfortunately, I'm running the community edition of neo4j so I cannot generate any server side logs.

I'd really like to get this running, any ideas or suggestions to determine the cause of this issue or provide a solution would be greatly appreciated.

I should add I'm running the latest version of the driver - 3.3.1.

Regards,
Benjamin

**Comment by inserpio** [comment]
Hi Benjamin, let us investigate a bit.
Could you by chance share that piece of code generating the issue?
Thanks!
Lorenzo

**Comment by jexp** [comment]
I very much hope you are using parameters for your large string list and not generating a query with a huge literal expression?
You can run neo4j enterprise as part of neo4j desktop and there also generate the relevant logs.

Are you running via bolt? What kind of profile does the browser show when your run your query with EXPLAIN / PROFILE ?

**Comment by n1zea144** [comment]
Thanks for the fast replies @inserpio @jexp.  Here is some more information - the code is being written to support a website with a Java/Spring/MyBatis-MySQL backend.  I'm prototyping the use of neo4j and have a MyBatis-neo4j implementation running alongside the MySQL implementation.  I am using bolt.

I'm not sure how helpful this is, but via the Mybatis logs, I can see the query taking the form:

`
match p=(s:sample)-[r]->(g:gene) where type(r) = "GENOMIC_PROFILE_ID_HERE" and s.stable_id in ["SAMPLE_1", "SAMPLE_2"...] return toInteger(g.entrez_gene_id) AS entrezGeneId, g.hugo_gene_symbol AS hugoGeneSymbol, count(p) AS totalCount, count(distinct[s,g]) AS countByEntity;
`

If I remove the 

`
and s.stable_id in [...]
`

clause, the query completes as expected.  I wasn't familiar with parameters until you mentioned them to me just now.  I will take a closer look.  I'll also look at neo4j desktop to get logging working.

I'm trying to get EXPLAIN/PROFILE results from the browser.  I'll provide them if/when the query completes.

**Comment by n1zea144** [comment]
Here is my PROFILE capture.  Putting the performance of the query on the back burner, the fact that the query completed in the browser but not in my java application has me scratching my head.  I would have pointed the finger at the mybatis library were in not for the fact that the same code runs when its backed by MySQL.  Which leads me to my first thought that maybe there is a timeout occurring between my code running in tomcat and the neo4j server?

PROFILE

![image](https://user-images.githubusercontent.com/366003/42388368-55399986-8113-11e8-807a-d78db74f3395.png)

**Comment by InverseFalcon** [comment]
Commenting on the query tuning side, your expansion and filter based on type is a bottleneck, that won't run efficiently. If you can change this so the type is explicitly on the relationship in the pattern, then this will be much faster:

```
match p=(s:sample)-[r:GENOMIC_PROFILE_ID_HERE]->(g:gene)
...
```

If the type is dynamic, then I'd advise using APOC pathfinding procedures to take care of the expansion instead:

```
match (s:sample)
where s.stable_id in ["SAMPLE_1", "SAMPLE_2"...]
call apoc.path.subgraphNodes(s, {relationshipFilter:'GENOMIC_PROFILE_ID_HERE>', labelFilter:'gene', maxLevel:1}) YIELD node as g
return toInteger(g.entrez_gene_id) AS entrezGeneId, g.hugo_gene_symbol AS hugoGeneSymbol, count(g) AS totalCount, count(distinct[s,g]) AS countByEntity;
...
```

Also your totalCount may not be giving you correct info back (either in this form or in your previous query) since the non-aggregation columns are your implicit grouping key (the entrez_gene_id and hugo_gene_symbol. You may need to do some collecting to get the count you need and then unwind back to rows.

**Comment by n1zea144** [comment]
Thanks @InverseFalcon .  I'm still learning the basics of Cypher queries, I need some time to absorb what you've written.

@inserpio @jexp for what its worth, I was able to capture a stack trace after forcibly removing my application from the tomcat container.   The driver appears to be attempting to read from a socket while attempting to close a transaction.  I thought if I let this run longer it would complete, but I havent had any success yet.

`
06-Jul-2018 18:18:03.838 WARNING [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ben-portal] is still processing a request that has yet to finish. This is very likely to create a memory leak. You can control the time allowed for requests to finish by using the unloadDelay attribute of the standard Context implementation. Stack trace of request processing thread:[
 sun.nio.ch.FileDispatcherImpl.read0(Native Method)
 sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
 sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
 sun.nio.ch.IOUtil.read(IOUtil.java:197)
 sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
 org.neo4j.driver.internal.security.TLSSocketChannel.channelRead(TLSSocketChannel.java:167)
 org.neo4j.driver.internal.security.TLSSocketChannel.unwrap(TLSSocketChannel.java:238)
 org.neo4j.driver.internal.security.TLSSocketChannel.read(TLSSocketChannel.java:434)
 org.neo4j.driver.internal.net.BufferingChunkedInput.readNextPacket(BufferingChunkedInput.java:412)
 org.neo4j.driver.internal.net.BufferingChunkedInput.readChunkSize(BufferingChunkedInput.java:348)
 org.neo4j.driver.internal.net.BufferingChunkedInput.read(BufferingChunkedInput.java:250)
 org.neo4j.driver.internal.net.BufferingChunkedInput.fillScratchBuffer(BufferingChunkedInput.java:219)
 org.neo4j.driver.internal.net.BufferingChunkedInput.readByte(BufferingChunkedInput.java:110)
 org.neo4j.driver.internal.packstream.PackStream$Unpacker.unpackStructHeader(PackStream.java:437)
 org.neo4j.driver.internal.messaging.PackStreamMessageFormatV1$Reader.read(PackStreamMessageFormatV1.java:411)
 org.neo4j.driver.internal.net.SocketClient.receiveOne(SocketClient.java:196)
 org.neo4j.driver.internal.net.SocketClient.receiveAll(SocketClient.java:190)
 org.neo4j.driver.internal.net.SocketConnection.receiveAll(SocketConnection.java:203)
 org.neo4j.driver.internal.net.SocketConnection.sync(SocketConnection.java:157)
 org.neo4j.driver.internal.net.ConcurrencyGuardingConnection.sync(ConcurrencyGuardingConnection.java:137)
 org.neo4j.driver.internal.net.pooling.PooledSocketConnection.sync(PooledSocketConnection.java:157)
 org.neo4j.driver.internal.ExplicitTransaction.close(ExplicitTransaction.java:115)
 org.neo4j.jdbc.bolt.impl.BoltNeo4jConnectionImpl.doCommit(BoltNeo4jConnectionImpl.java:136)
 org.neo4j.jdbc.bolt.BoltNeo4jPreparedStatement.executeInternal(BoltNeo4jPreparedStatement.java:101)
 org.neo4j.jdbc.bolt.BoltNeo4jPreparedStatement.execute(BoltNeo4jPreparedStatement.java:77)
....
`

**Comment by omarlarus** [comment]
Hi @n1zea144 ,
what is the query of the PROFILE you posted? I think it's the one of the query without the IN clause, because I can't see the filter part refer to it.
It's very strange a query that works on the browser doesn't work on the JDBC. I tested that and the execution time for your very long query is quite the same on browser and on jdbc.
Reading the exception you posted it seems the query it's taking lots of time, but the execution time should be very similar with the browser one. So, how long it takes in your browser?
