### ISSUE TITLE
Squirrel (jre 1.8) complaining about the driver is not JDBC 2.1 compliant

### ISSUE THREAD

**Issue by adriens** [neo4j/neo4j-jdbc#163]
![2018-08-21 08_36_13-about](https://user-images.githubusercontent.com/5235127/44368047-4ed4be80-a51d-11e8-8452-4e25cbde8b9f.png)

![bug](https://user-images.githubusercontent.com/5235127/44368004-2b117880-a51d-11e8-946b-e06964f53dae.png)

Still the queries are running.

**Comment by adriens** [comment]
Here is jre version :

![2018-08-21 08_40_32-squirrel sql client snapshot-20180815_2231](https://user-images.githubusercontent.com/5235127/44368222-e6d2a800-a51d-11e8-856a-2c8949e5be62.png)

**Comment by omarlarus** [comment]
Hi @adriens ,
can you provide us the connection parameters and the exact version of the neo4j jdbc driver?

**Comment by adriens** [comment]
Hi @omarlarus , i've downloaded the latest available jar provided in the latest release : `neo4j-jdbc-driver-3.4.0.jar`

**Comment by adriens** [comment]
Here are the driver properties i used :
![2018-08-22 20_40_18-squirrel sql client snapshot-20180815_2231](https://user-images.githubusercontent.com/5235127/44456222-b12bdd00-a64b-11e8-8ab5-af793725eb7e.png)

**Comment by adriens** [comment]
Are these datas enough for you ? If not, please tell me what to provide you. In fact i've used default properties,  hope this helps 😸

**Comment by omarlarus** [comment]
Thanks @adriens . There's this [PR](https://github.com/neo4j-contrib/neo4j-jdbc/pull/164) that fix the issue. You can test a preview downloading the jar from [here](https://www.dropbox.com/s/cy9m38z9ttngvl1/neo4j-jdbc-driver-3.4.0.jar?dl=0). Let us know if it works, please.

**Comment by adriens** [comment]
I've just downloaded it : I give it a ry right now. I'll let you know ASAP.

**Comment by adriens** [comment]
Just replaced the previous jar by this one : it does the job : ***no more warning*** 👍 
Thanks a lot for the fix !

**Comment by adriens** [comment]
Thanks to your help i could release my latest linkedIn article 😃 
https://www.linkedin.com/pulse/digging-mining-datas-structures-extracting-from-neo4j-adrien-sales/
