### ISSUE TITLE
BoltRoutingNeo4jDriver - Issue with Boolean Data type

### ISSUE THREAD

**Issue by tusharranjan2904** [neo4j/neo4j-jdbc#179]
We automate tests to execute services and validate data from Neo4j. We recently moved to using the Bolt Routing Driver for our tests(org.neo4j.jdbc.boltrouting.BoltRoutingNeo4jDriver). After this we are facing an issue when the datatype is Boolean. It’s always returned as “null”. 
We are using “neo4j-jdbc-driver-3.4.0.jar” to insert and retrieve data from Neo4j. Earlier we were using “neo4j-jdbc-2.1.4.jar” and "org.neo4j.jdbc.Driver" and we were able to get data for Boolean fields as well. I am able to get long, integers and string data from both Drivers.

I have tried simple JDBC Connection,Statement and Result set to fetch the values and found the same issue

**Comment by inserpio** [comment]
Hi @tusharranjan2904, I got informed by the neo4j support team that you're facing this issue.
If you're fine, as soon as we identify (and solve) the problem, we (@larusba) will send you a snapshot jar, so that you can test whether our patch solves the issue or not.
We'll keep you update.

**Comment by tusharranjan2904** [comment]
Thanks a lot !

**Comment by tusharranjan2904** [comment]
Hi @omarlarus! Is there an ETA to when I can get the updated jar for this. All my automation tests are failing because of this.

**Comment by AngeloBusato** [comment]
Hi @tusharranjan2904, we did some tests and updated the driver. You can try with this new one and give us a feedback if the issue is solved. 

[neo4j-jdbc-driver-3.4.0.jar.zip](https://github.com/neo4j-contrib/neo4j-jdbc/files/2822500/neo4j-jdbc-driver-3.4.0.jar.zip)

**Comment by conker84** [comment]
Hi @tusharranjan2904 any feedback about the jar provided by @AngeloBusato ?

**Comment by dgordon5483** [comment]
@conker84 @AngeloBusato I have received confirmation that @tusharranjan2904 and team has tested this and it resolves the issue, thanks! Can you please merge and release a new version of the JDBC driver at your convenience? Thanks!
