### ISSUE TITLE
Possible bug: possible HTTP connection pool exhaustion

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#18]
https://github.com/fbiville/liquigraph/issues/82 reveals that for the last Liquigraph changeset insertion into Liquigraph history graph, the main thread hangs forever because it forever waits for a connection from Apache HTTP connection pool (you can see the actual main thread dump in the original issue).

This happens with the legacy JDBC driver.

Maybe it happens with the new one as well.

To emulate Liquigraph behaviour, the idea would be to hold a single JDBC connection and commit several transactions during that time. The test input Liquigraph data roughly inserts ~100 nodes and connections (via `MERGE`) in ~30 transactions when the exhaustion kicks in.

I can share the input data privately if it helps.

**Comment by fbiville** [comment]
Most of Liquigraph JDBC-related logic lives [here](https://github.com/fbiville/liquigraph/tree/master/liquigraph-core/src/main/java/org/liquigraph/core/io).

**Comment by jexp** [comment]
@fbiville Can you create a test that reproduces the issue?

**Comment by fbiville** [comment]
OK, I'll do that this week.

**Comment by jexp** [comment]
@fbiville did you find time for this?

**Comment by fbiville** [comment]
Oops, escaped my radar. Let me try tomorrow.
