### ISSUE TITLE
SQL to Cypher conversion

### ISSUE THREAD

**Issue by albertodelazzari** [neo4j/neo4j-jdbc#183]
Some query tools cannot handle Cypher and expect an SQL statement to pass thru the JDBC connection. Therefor a SQL to Cypher connversion would be helpful. This should support at least simple SQL statements where tables, columns, joins and where clauses are converted to a Cypher/Neo4j equivalent.

It comes from the old Larus project

See also [the original issue](https://github.com/larusba/neo4j-jdbc/issues/1)

**Comment by jexp** [comment]
Handled by the BI Connector: https://neo4j.com/bi-connector/
