### ISSUE TITLE
BoltStatement closes transaction when statement is closed and autoCommit was disabled

### ISSUE THREAD

**Issue by mvitz** [neo4j/neo4j-jdbc#20]
I think this is a bug, because when I disable auto commit I don't want the transaction to be marked as failure and be closed after I close a single statement...

**Comment by jexp** [comment]
Yes Transactions are bound to connections, not statements in jdbc. 

Can you add a failing test?

Von meinem iPhone gesendet

**Comment by mvitz** [comment]
See #22 for a test and a provided solution.
Maybe I'm missing something there as there was a test to check exactly that closing a statement closes the transaction but I think the new behaviour fits more ;-)

**Comment by albertodeste** [comment]
It was a misunderstanding situation that leaded to this bug, I now merged the pull request so it is fixed! Thank you mvitz for the fix!

**Comment by mvitz** [comment]
No problem ;-) I looked at my commits again and found a few more refactorings I think are helpful. I will provide a new PR when I have time ;-)
