### ISSUE TITLE
JDBC URL parameters with '&' and ',' fails

### ISSUE THREAD

**Issue by oyvindwe** [neo4j/neo4j-jdbc#200]
We discovered this when running [Liquigraph](https://www.liquigraph.org/) against Neo4j, with a user that had `&` in the password. Liquigraph builds a JDBC URL with username and password as parameters (using `,` as parameter separator). We first believed the problem was caused by Liquigraph not URL encoding username and password when building the JDBC string, but URL encoding the password before passing it to Liquigraph still failed.

The problem is at line 118 in `org.neo4j.jdbc.Neo4jDriver`, where the entire query string of the URL is decoded before it is split on `[,&]`. Double encoding the password will not work either, as the parameters are not decoded after the split. The code should first split on `[,&]`, and then doURL decode each parameter key/value pair, before looking for the first `=` or `:`. This change should be fairly backwards compatible in my opinion.

I believe it is more correct to look for `=` or `:` before decoding, but that is prone to be be less backwards compatible with existing connection strings.

I am happy to submit a PR to fix this.

**Comment by fbiville** [comment]
Is there a reason this issue is still open?

**Comment by oyvindwe** [comment]
Probably not, as the fix is merged. There hasn't been a release in a long time though.
