### ISSUE TITLE
Slowness observed in obtaining connection using neo4j java jdbc driver

### ISSUE THREAD

**Issue by kamathsachin7** [neo4j/neo4j-jdbc#203]
Hi All,

I have my java application deployed in websphere application server. I am successfully able to connect to neo4j from my java application using jdbc driver. But there are some performance issues with the approach i have followed. Currently neo4j server is running on Xms - 8G and Xmx-16GB. I have only less amount of data that is aprox 40mb with 3100 nodes. When we test the performance over http with cypher, the performance is outstanding. But with the java application we are using the jdbc driver to connect to neo4j via bolt. Every connection creation is taking around 100ms which is adding up delay. We are able to achieve only 160 hits/sec with this approach. With 500 concurrent calls, the requests are queuing up and the response time is shooting to 3 seconds. Any pointers of improvement would be helpful. (Application server and neo4j servers are on different boxes under the same VLAN).

Below is the snippet of connection creation.
Class.forName("org.neo4j.jdbc.Driver").newInstance();
Connection conn = DriverManager.getConnection("jdbc:neo4j:bolt://localhost:port") ;

**Comment by jexp** [comment]
Which version do you use?

What happens if you reuse the same driver or connection?

**Comment by kamathsachin7** [comment]
@jexp Im using neo4j version 3.3.9 with neo4j driver 3.3.1. 

Here for every transaction the connection is opened and closed which is causing the slowness.

As of now it looks like i the issue is due to the connection pool not being set.

Im trying to create data source for neo4j in websphere application server but its failing to connect. Any pointers on this would be helpful.

JDBC Driver Created with the following parameters:
Name : neo4j Driver
Class path : path of the neo4j jdbc jar/neo4j-jdbc-driver-3.3.1.jar
Implementation class name : org.neo4j.jdbc.Driver
Data source created with the following :
jndi Name: jdbc/neo4j
Custom Properties:
auth : container
type: javax.sql.DataSource
username: neo4j
password: password
url:jdbc:neo4j:bolt://localhost:port
removeAbandonedOnBorrow : true
closeMethod : close
The properties are added based on the pointers provided in https://github.com/neo4j-contrib/neo4j-jdbc

Here is the error from logs:

**java.lang.Exception: DSRA8101E: DataSource class cannot be used as one-phase: ClassCastException: org.neo4j.jdbc.bolt.BoltDriver incompatible with javax.sql.ConnectionPoolDataSource** 
[5/27/19 13:12:41:533 UTC] 00000111 SystemErr R at com.ibm.ws.rsadapter.AdapterUtil.createDataStoreAdapterException(AdapterUtil.java:441) 
[5/27/19 13:12:41:533 UTC] 00000111 SystemErr R at com.ibm.ws.rsadapter.DSConfigHelper.getPooledConnection(DSConfigHelper.java:1340)

**Comment by kamathsachin7** [comment]
@jexp Got to know from the other forum that Websphere doesnt support to create datasource for neo4j.

https://stackoverflow.com/questions/56336920/error-when-creation-data-source-for-neo4j-in-websphere-application-server

Can you please help me on how we can achieve connection pooling ?

**Comment by jexp** [comment]
The Neo4j Driver that the JDBC driver wraps pools connections internally.
There should be no need to created individual connections.

Can you see if this build helps you, it includes a change that reuses driver objects by settings/url.

https://www.dropbox.com/s/7w8ad2ln5dz41od/neo4j-jdbc-driver-3.4.0.jar?dl=0

**Comment by fbiville** [comment]
Closing this as we have not heard back.
