### ISSUE TITLE
noe4j jdbc Siren.io and Windows

### ISSUE THREAD

**Issue by juliaglen** [neo4j/neo4j-jdbc#205]
I am running Neo4J on Windows in AWS. I want to use siren.io. However, I get the error when testing the connection using 
jdbc::neo4j:http://localhost:11002
and
jdbc::neo4j:http://localhost:7474

Any suggestions?

Thanks

**Comment by jexp** [comment]
Which error are you getting?

Doesn’t siren support neo4j out of the box via the bolt driver?

**Comment by juliaglen** [comment]
This is the error I am getting.

Could not validate datasource [MVP]. {“error”:{“root_cause”:[{“type”:“exception”,“reason”:“Could not validate datasource [MVP].”}],“type”:“exception”,“reason”:“Could not validate datasource [MVP].”,“caused_by”:{“type”:“s_q_l_transient_connection_exception”,“reason”:“MVP-pool - Connection is not available, request timed out after 30072ms.”}},“status”:500}

https://community.siren.io/t/testing-connection-to-neo4j-fails/103/2

Thanks

**Comment by jexp** [comment]
Which JAR did you use?

And can you try the bolt URL instead?

**Comment by jexp** [comment]
Did the answers from the other siren folks help you?

**Comment by fbiville** [comment]
Closing this as we never heard back.
@juliaglen feel free to reopen if you get more information at this point.
