### ISSUE TITLE
Direct file connection

### ISSUE THREAD

**Issue by VincentBlouin** [neo4j/neo4j-jdbc#207]
Hello, in version 2.x, I used to connect using "jdbc:neo4j:instance:{database_name}"  using what I think is "direct file connection". Is this implemented in 3.x yet ? If not do you have an idea of when it would be? 

Thank you.

I fear that if I were to use bolt that the performance would be significantly impacted unless I were to migrate a lot of my queries in procedures is that right ?

Also how to connect using embedded ? Thank you.

**Comment by fbiville** [comment]
Hello, we are not going to implement it.
For embedded, you can open a local Bolt connector and connect with Bolt.
