### ISSUE TITLE
Neo4j-JDBC doesn't work with neo4j-java-driver 4.0+

### ISSUE THREAD

**Issue by michael-simons** [neo4j/neo4j-jdbc#208]
Due to various changes in both packages and API, Neo4j-JDBC won't work with the upcoming Bolt-Driver.

There is no easy / possible way to have both on the class path (1.7.x and 4.x), so there's a need for an updated JDBC driver.

**Comment by jexp** [comment]
Separate release/branch

updates similar to: https://github.com/neo4j/neo4j-ogm/commit/0abfefb2b5bacc291a230a111fe2ad21974ede0f

**Comment by ctytgat** [comment]
Any idea when this would be available? 
This is actually blocking anyone wishing to upgrade to spring boot 2.2 + OGM 3.2.2 ... :-/
(OGM 3.2.2 depends on neo4j-java-driver 4.0.0-beta02)

**Comment by ctytgat** [comment]
@conker84 Any idea when we could expect a release with the new driver?

**Comment by conker84** [comment]
@ctytgat the next week we'll do a beta release
