### ISSUE TITLE
Native connection pooling

### ISSUE THREAD

**Issue by sey** [neo4j/neo4j-jdbc#212]
I'm using MyBatis with Spring in 2 different projects.  
One uses the 3.3.1 JDBC Bolt driver and the other uses the 3.4.0 JDBC Bolt driver.  
The nice addition coming from 3.4.0 is that it will support LocalDateTime for instance.  

With the later one I get a lot of logs like the following (for every request almost)
```
Driver.info - Direct driver instance 1913113483 created for server address 127.0.0.1:7777
Driver.info - Closing driver instance 1913113483
ConnectionPool.info - Closing connection pool towards 127.0.0.1:7777
```
It feels like the underlying connection pool of Neo4j is never used (every connection will create a connection pool and close it after usage).  

With the former one I don't see those logs but it seems like the behaviour is the same in the end.  
Both JDBC drivers rely on different connection pool implementation from Neo4j Java Driver (SocketConnectionPool (1.4.6) for 3.3.1 and ConnectionPoolImpl (1.6.1) for 3.4.0).  
When I use the JDBC driver 3.4.0 I see performance issues for each connection that I didn't notice with 3.3.1.  

I was able to reproduce this behaviour outside of MyBatis by just using DriverManager.getConnection().
As I'm using Spring I also tried to play a bit with HikariDataSource as it is a great connection pool.  
But of course configuring the driver class name to the JDBC BoltDriver results in following the same code path creating the native Neo4j connection pool and closing it every time.

Both driver versions use GraphDatabase.driver() every time you request a connection which should only be called once per application (for simple needs) as per the Neo4j Java driver documentation.

Is this designed on purpose? or is it just a problem due the JDBC interfaces?  
Is there a way to use the native connection pool from the JDBC driver?  
Or did I miss something here?

**Comment by sey** [comment]
Investigating a bit further, I think the `BoltNeo4jConnectionImpl` should not be responsible for closing the driver. 

Doing this quick and dirty fix, I have no performance issues.
```
// BoltNeo4jDriverImpl.connect()
                if (currentDriver == null) {
                    currentDriver = getDriver(routingUris, config, authToken, info);
                }

// BoltNeo4jConnectionImpl
	public void closeSession(Session session){
		if (session != null) {
			session.close();
//			this.driver.close();
		}
	}
```

How to close the driver when the app terminates needs to be discussed if this is the way to go.

**Comment by jexp** [comment]
@conker84 can you investigate this?

https://github.com/neo4j-contrib/neo4j-jdbc/blob/3.5/neo4j-jdbc-bolt/src/main/java/org/neo4j/jdbc/bolt/impl/BoltNeo4jConnectionImpl.java#L264

**Comment by michael-simons** [comment]
This does not apply to version 6 anymore.

@sey We are aware that this ticket is a bit old ;) But if you still interested in our driver, please head out to try out version 6: https://github.com/neo4j/neo4j-jdbc/releases/tag/6.0.0-M01 

First milestone is available on central already, with at least one more to come.

Also we do test with MyBatis,
