### ISSUE TITLE
3.4.0 jdbc driver lacks ability to pass multiple bookmarks to initial session

### ISSUE THREAD

**Issue by owaincole** [neo4j/neo4j-jdbc#213]
The java drivers support passing of  a collection of bookmarks to the initial session, in order to enable a new session being sychronised with multiple other sessions.
Indeed, the example in the docs uses this funcationality ( https://neo4j.com/docs/developer-manual/3.4/drivers/sessions-transactions/ )

However the jdbc driver only supports a single bookmark. This means we cannot synchronize the output of multiple sessions.

Please can we enable the passing of multiple bookmarks so that the initial session can support non-trivial sychronisation.
Thanks,
Owain

PS Code copied below showing the new session creation - note the String for bookmarks. And the driver methods showing both single and multiple bookmarks

 org.neo4j.jdbc.bolt.impl.BoltNeo4jDriverImpl
```
	public Session newNeo4jSession(){
		try {
			String bookmark = this.getClientInfo(BoltRoutingNeo4jDriver.BOOKMARK);
			return this.driver.session(getReadOnly() ? AccessMode.READ : AccessMode.WRITE, bookmark);
		}
```

org.neo4j.driver.v1.Driver...
```
  Session session( AccessMode mode, String bookmark );
  Session session( AccessMode mode, Iterable<String> bookmarks );
```

**Comment by conker84** [comment]
[neo4j-jdbc-driver-3.4.0.jar.zip](https://github.com/neo4j-contrib/neo4j-jdbc/files/4059144/neo4j-jdbc-driver-3.4.0.jar.zip)
Hi @owaincole can you test the jar above? Please refer to the following snippet to understand how you can do it:

https://github.com/neo4j-contrib/neo4j-jdbc/blob/08e78b5ccf0148f6b34f526159b56361595212e6/neo4j-jdbc-bolt/src/test/java/org/neo4j/jdbc/boltrouting/BoltRoutingIT.java#L148-L168

**Comment by owaincole** [comment]
Thanks, it certainly looks like it should work from the classes.
We had held back utilizing the read-only nodes in the cluster until now, but I think that's the final hurdle cleared to allow us to start on that element of the development.
We'll begin testing now.
