### ISSUE TITLE
Neo4j-jdbc-driver issue - All the requests are routed to "LEADER” in the cluster group

### ISSUE THREAD

**Issue by Ram2929** [neo4j/neo4j-jdbc#216]
We were using neo4j JDBC driver (neo4j-jdbc-driver-3.4.0.jar) which is capable for using BOLT+ROUTING protocol, and trying to connect from NO-SQL(Apache Solr) to pull data from Neo4J to Solr. 
 
We do not have solr source code, we did the data source configuration in EAP where Solr is installed and using the JNDI, Solr is connecting to Neo4J to fetch data. 

While doing so, we see all the requests are getting routed to "LEADER” in the cluster formation.
 
We wanted to know if there is a configuration in (neo4j-jdbc-driver-3.4.0.jar)using which can force Solr to open read-only connection and distribute the load among the available cluster instances.

PFB the data source configuration in EAP – Any feedback in this regards would be highly helpful. Thanks
 
<datasource jta="true" jndi-name="java:jboss/NEO4J_ENTMT2" pool-name="Neo4j-3.4-drvier" enabled="true" use-ccm="true">
                    <connection-url>jdbc:neo4j:bolt+routing://10.23.233.179:12061,10.23.233.179:12062,10.23.233.179:12063,10.23.233.184:12061,10.23.233.184:12062</connection-url>
                    <driver-class>org.neo4j.jdbc.boltrouting.BoltRoutingNeo4jDriver</driver-class>
                    <driver>neo4j-jdbc-driver-3.4.0.jar_org.neo4j.jdbc.boltrouting.BoltRoutingNeo4jDriver_3_2</driver>
                    <security>
                        <user-name>neo4j</user-name>
                        <password>xxxxxx</password>
               </security>
</datasource>

**Comment by jexp** [comment]
you need to use read-only connections to be routed to other cluster members

not sure if that's exposed through config as well or just in the java sql Connection API @conker84

**Comment by jexp** [comment]
We fixed that in recent version, if you pass readonly=true as config parameter to the URL it will _only_ use readonly sessions which should go to the followers and read-replicas.

If you don't have access to the JDBC con.setReadonly() API
