### ISSUE TITLE
Enable Read Only property via connection string

### ISSUE THREAD

**Issue by rhaces** [neo4j/neo4j-jdbc#218]
Currently, to mark a transaction as read only and have the driver distribute it to read members of the cluster, you need to use the method `setReadOnly` method (`connection.setReadOnly(true);`). However this is only accessible via code, if you are using a 3rd party client and don't have access to the code, there is no way to do this, making all calls go to the LEADER.

Enable a way to tell the jdbc that the statement is read only, could be via a parameter passed in the connection string or some other functionality that does not require code change in the 3rd party tools.

**Comment by conker84** [comment]
Hi @rhaces can you test the following jar?
You should be able to pass the readOnly flag in this way:

`jdbc:neo4j:bolt://localhost?readOnly=true`

[neo4j-jdbc-driver-3.4.0.jar.zip](https://github.com/neo4j-contrib/neo4j-jdbc/files/4309231/neo4j-jdbc-driver-3.4.0.jar.zip)

**Comment by rhaces** [comment]
After testing the attached driver with SquirrelSQL, I don't see that the flag is working, I'm setting up SquirrelSQL as shown below and I can still send a "CREATE" cypher, where if the readTransaction is correctly being used, the cypher would fail.

Class Name: `org.neo4j.jdbc.Driver` and `org.neo4j.jdbc.boltrouting.BoltRoutingNeo4jDriver`
URL: `jdbc:neo4j:bolt+routing://localhost:7627?readOnly=true`
Jar file used:
```
$ ls -ls /home/rodrigo/Downloads/neo4j-jdbc-driver-3.4.0.jar
5848 -rw-r--r-- 1 rodrigo rodrigo 5985110 Mar  9 18:29 /home/rodrigo/Downloads/neo4j-jdbc-driver-3.4.0.jar
$ md5sum /home/rodrigo/Downloads/neo4j-jdbc-driver-3.4.0.jar
3ca3d3b94921f87992cfdeaedd25503d  /home/rodrigo/Downloads/neo4j-jdbc-driver-3.4.0.jar
```

**Comment by rhaces** [comment]
After doing some additional debug, the issue is that we are calling the variable `readOnly` however the `getProperties()` for some reason brings the properties all lowercased, not sure if this is a JDBC standard or something else. See the two attached screenshots, notice how in the first one `readOnly=false` and when I evaluate `getProperties` I see  (second screenshot) `readonly=true`
![Screenshot_20200319_140309](https://user-images.githubusercontent.com/1266195/77100973-e7c70680-69ec-11ea-9ea3-a7bc2f755709.png)
![Screenshot_20200319_140812](https://user-images.githubusercontent.com/1266195/77100977-ea296080-69ec-11ea-9c6d-2650a554bba1.png)
