### ISSUE TITLE
Restore Cluster Test

### ISSUE THREAD

**Issue by conker84** [neo4j/neo4j-jdbc#224]
Restore Cluster Test

**Comment by michael-simons** [comment]
In version 6 we have https://github.com/neo4j/neo4j-jdbc/blob/4a2d40218f1e31c30d46c75574add911b7ce5e54/neo4j-jdbc-it/neo4j-jdbc-it-cp/src/test/java/org/neo4j/jdbc/it/cp/ClusterIT.java#L57
