### ISSUE TITLE
Make using bookmark configurable via connection URL property

### ISSUE THREAD

**Issue by ckazz** [neo4j/neo4j-jdbc#229]
To make using bookmarks optional by making it configurable via connection URL property.

**Comment by jexp** [comment]
@conker84 for a customer

**Comment by conker84** [comment]
Hi @ckazz can you please try the following jar:
[neo4j-jdbc-driver-4.0.0.jar.zip](https://github.com/neo4j-contrib/neo4j-jdbc/files/4735367/neo4j-jdbc-driver-4.0.0.jar.zip)

You can use it in the following way:

`jdbc:neo4j:bolt://localhost?usebookmarks=false`

**Comment by conker84** [comment]
@ckazz please check the md5  of the file ` c372058e230ff2547253afc3d6eca267`

**Comment by ckazz** [comment]
Thank you @conker84 
Forwarding to user and will update once they have tested.
