### ISSUE TITLE
getRowId in class org.neo4j.jdbc.Neo4jResultSet is not yet implemented

### ISSUE THREAD

**Issue by avgoustak** [neo4j/neo4j-jdbc#239]

**Comment by fbiville** [comment]
Hi @avgoustak, thanks for the report.
I looked at the JDBC drivers of MySQL, MSSQL and Postgres for inspiration, and they do not support that feature either.

Can you share how you got that error? Are you using a specific tool? Thanks in advance!

**Comment by fbiville** [comment]
Closing this as we have not heard back.
