### ISSUE TITLE
JDBC Prefix different to 2.x

### ISSUE THREAD

**Issue by mvitz** [neo4j/neo4j-jdbc#24]
The previous JDBC prefix was `jdbc:neo4j:...`. I like the new Prefix with `jdbc:bolt:..` and `jdbc:http:..` however I'm not sure that `jdbc:http:..` without any neo4j hint feels right. Maybe using `jdbc:neo4j:http:..` would be better?

**Comment by sim51** [comment]
For me it's just redundant with the driver class, but I see your point.

If we add the neo4j prefix, we must adding it to all url. 
So do you prefer solution 1 or 2 ?
- `jdbc:bolt://localhost` & `jdbc:http://localhost` (1) 
- `jdbc:neo4j:bolt://localhost` & `jdbc:neo4j:http://localhost` (2)

**Comment by mvitz** [comment]
I think there are some tools that infer the driver class from the URI. Currently I would prefer solution 2.

**Comment by ralfbecher** [comment]
I agree, this seems to be important in mixed environments.

**Comment by jexp** [comment]
I would also prefer solution 2!

**Comment by albertodeste** [comment]
In my opinion solution 2 is much more clean and clear.
