### ISSUE TITLE
Does this Driver work with Apache Nifi

### ISSUE THREAD

**Issue by dbapundit** [neo4j/neo4j-jdbc#254]
If so, can you provide an example of this working using these products? Thanks

**Comment by michael-simons** [comment]
Thanks for opening this issue. It helped us to discover a bug in the milestone M01 of our upcoming version 6.
I am happy to tell you this will work in Apache Nifi. See attached screenshots and the workflow.

It works both with individual queries and just dumping tables.

![nifi3](https://github.com/neo4j/neo4j-jdbc/assets/526383/e14ff8f9-85ab-4b50-8b36-e304f958ef0b)
![nifi2](https://github.com/neo4j/neo4j-jdbc/assets/526383/d57a7ff2-2536-4e68-810d-3104a4d1528c)
![nifi1](https://github.com/neo4j/neo4j-jdbc/assets/526383/69c28058-0fb4-40aa-96d8-3df0967837d5)
[NiFi_Flow.json](https://github.com/neo4j/neo4j-jdbc/files/14462595/NiFi_Flow.json)
