### ISSUE TITLE
Shading of all artefacts by design

### ISSUE THREAD

**Issue by mvitz** [neo4j/neo4j-jdbc#26]
I just discovered that all artefacts are shaded by default. I personally would prefer to not doing that to not conflict with potentially other Neo4J artefacts on the classpath. But to provide a single JAR that can be used by a SQL tool that is a nice feature.

This ticket is primarily to document the decision that was taken by you and why. :-)

**Comment by sim51** [comment]
Thanks @mvitz for your feedback !

As you said, the goal is to provide a single jar (with all deps)  that can be easely used by a SQL tool.
And for each protocol (bolt & http) we have a dedicate maven project, so we can provide a jar that only match user's needs.

Moreover, we take care about what we have included as deps. For now there is only 3 : 
- httpclient & jackson for the http driver (no more deps to jaxrs like in the previous version)
- neo4j-bolt-driver for bolt

We can't do less :)

And if you want to use this driver in a project, you should include it as a maven deps, so you will be able to manage dependencies.

Do you have in mind a case that can be a problem ?

Cheers.

**Comment by mvitz** [comment]
I don't have a specific case in mind but I'm aware that using shaded libraries can lead to problems. I remember some cases (with hadoop) were there were multiple jackson versions.

Shading could also be a licence problem (because technically) it's a redistribution. Maybe it would be a good idea to put these shaded classes into another package. Then interference in a project couldn't be any problem.
