### ISSUE TITLE
Manage `Statement#getMoreResults` properly

### ISSUE THREAD

**Issue by conker84** [neo4j/neo4j-jdbc#270]
Based on its official JavaDoc:

> Moves to this Statement object's next result, returns true if it is a ResultSet object, and implicitly closes any current ResultSet object(s) obtained with the method getResultSet.

With @fbiville we decided to do that in this way:

* first call of getMoreResults returns true since the result is a RS, and this RS will then be closed
* second call of getMoreResults returns false since there is no current RS anymore (OR we check RS is closed)

This bug came out from https://github.com/liquibase/liquibase-neo4j/issues/14

**Comment by fbiville** [comment]
For reference, the current implementation of `getMoreResults` (for Bolt) causes the execution of Cypher queries with `RETURN` clauses to hang forever when running in Liquibase (see detailed comment [here](https://github.com/liquibase/liquibase-neo4j/issues/14#issuecomment-885528077)).
