### ISSUE TITLE
Improve RETURN clause detection

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#272]
`BoltNeo4jStatement` currently performs [a naive string match](https://github.com/neo4j-contrib/neo4j-jdbc/blob/6b79aa5a88936e7f7fab82fef86d531a07edad6c/neo4j-jdbc-bolt/src/main/java/org/neo4j/jdbc/bolt/BoltNeo4jStatement.java#L107) to detect whether a query returns a result or not.

As discussed [here](https://github.com/liquibase/liquibase-neo4j/issues/14#issuecomment-885937348), this can create false positives. For the record, the example in that other issue was:

```cypher
CALL apoc.periodic.commit("MATCH ... CALL apoc.refactor.mergeNodes(...) YIELD node RETURN count(*)", {limit:10000})
```

The main query does not have a `RETURN` clause, yet `BoltNeo4jStatement` will think otherwise. 

Couple that with the recently fixed https://github.com/neo4j-contrib/neo4j-jdbc/issues/270 (but not yet released), and you get forever-hanging queries that should not even get `ResultSet`s in the first place.

**Comment by conker84** [comment]
I think that we can leverage the `EmptyResult` operator returned from the plan. If is present, the query will not return any result
