### ISSUE TITLE
Driver may not close properly when running multiple sessions

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#286]
Currently, `org.neo4j.jdbc.bolt.cache.BoltDriverCached` keeps track of the number of sessions the underlying Java driver opens. 
Upon closure, `org.neo4j.jdbc.bolt.cache.BoltDriverCached` prevents its own eviction from the driver cache and the underlying Java driver closure if there are any open sessions.

However, the problem is that the counter is never decremented when a session closes. As soon as `org.neo4j.jdbc.bolt.cache.BoltDriverCached` is used for more than 1 session, it will leak itself and its underlying driver since they both will never close.

**Comment by michael-simons** [comment]
Not applicable anymore for Version 6.
