### ISSUE TITLE
cannot connect to neo4j aura DB

### ISSUE THREAD

**Issue by sarce666** [neo4j/neo4j-jdbc#290]
hello 
the aura db only ahtorize neo4j+s to connect to 
when i try connect to my aura cloud db , i get this error 
│   Error: LoadError: no such file to load -- sequel/adapters/neo4j+s                                                                                                               │
│   Exception: Sequel::AdapterNotFound                                                                                                                                              │
│   Stack: org/jruby/RubyKernel.java:974:in `require'  
thnsk
what url should put ? mine is neo4j+s://xxxxxx.io:7687

**Comment by fbiville** [comment]
Hi, can you share your project setup in more details?
What dependencies are you using (at which version)?

**Comment by fbiville** [comment]
Feel free to reopen this once you have more information.
