### ISSUE TITLE
Method supportsStoredProcedures in class org.neo4j.jdbc.DatabaseMetaData is not yet implemented.

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#31]
In SquirrelSQL

Error: neo4j-test: java.lang.UnsupportedOperationException: Method supportsStoredProcedures in class org.neo4j.jdbc.DatabaseMetaData is not yet implemented.

**Comment by ralfbecher** [comment]
occurs on connect

**Comment by jexp** [comment]
fixed, returns false now
