### ISSUE TITLE
Liquibase Plugin for Neo4j not working

### ISSUE THREAD

**Issue by dtendo** [neo4j/neo4j-jdbc#314]
Installed liquibase and copied the jar file in the appropriate folder. I still can't connect to neo4j though.

`Unexpected error running Liquibase: java.lang.RuntimeException: Cannot find database driver: org.neo4j.jdbc.bolt.BoltDriver`

**Comment by fbiville** [comment]
Thanks for reporting. I just noticed a similar bug has been reported in the [Liquibase repository](https://github.com/liquibase/liquibase-neo4j/issues/147), so I'm going to close this one.
