### ISSUE TITLE
Squirrel SQL array values don't work

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#35]
returned as nulll

```
actor.name                                r.roles  movie.title                               
---------------------------------------------------------------------------------------------
Tom Hanks                                 <null>   That Thing You Do                         
Tom Hanks                                 <null>   Joe Versus the Volcano                    
Tom Hanks                                 <null>   Sleepless in Seattle                      
Tom Hanks                                 <null>   You've Got Mail                           
Tom Hanks                                 <null>   Charlie Wilson's War                      
Tom Hanks                                 <null>   The Polar Express      
```

<img width="1568" alt="squirrel sql client version 3 7 1-1" src="https://cloud.githubusercontent.com/assets/67427/15895193/4b9af980-2d8a-11e6-98fc-e066e37cefe7.png">

**Comment by ralfbecher** [comment]
r.roles[0] etc. works

**Comment by albertodeste** [comment]
This bug seems related to the SquirrelSQL way to manage java.sql.Array (SQL type = 2003), In the previous version of the driver it used to work because the array was returned as a String so everything worked fine. 
I tried a specific approach for SquirrelSQL but I can't find a System.property which is related to it. 
Do you have ideas? Personally I prefer to return a java.sql.Array instead of a String (as a default behaviour).

**Comment by glaggia-larus** [comment]
> There is currently no DataTypeComponent for "array" types (Object Tree), and
no support in ResultSetReader for "array" types as well (SQL ResultSet
Panel).  You could add  a custom data type for Postgres to populate the
contents tab in the object tree.  However, we need to add support in
ResultSetReader as this is not currently plugin-accessible.  You could
submit a feature request.  Patches are also welcome.

this is what the squirrel team said about this problem (as far as in march 2011)
We can assume this is not related to the driver itself and so I close the issue.

To see a human readable result you can use something like this on the array:

```reduce(str = '', role in r.roles | role + ',' + str)```
