### ISSUE TITLE
Performance issues caused by driver fetching behaviour

### ISSUE THREAD

**Issue by dam-mond** [neo4j/neo4j-jdbc#363]
Currently, the JDBC driver fetches all the returned records from a query in memory, ignoring any other settings, due to the following line: https://github.com/neo4j-contrib/neo4j-jdbc/blob/4.0/neo4j-jdbc-bolt/src/main/java/org/neo4j/jdbc/bolt/BoltNeo4jResultSet.java#L113.

This can potentially cause a high memory utilisation in case of queries returning many records, which causes performance issues.
The expectation is that the driver should not fetch all the returned records at once unless a specific setting is enabled (for example, when flattening is set to -1).

**Comment by owaincole** [comment]
Hi, I'm additionally worried that the sychronised keyword on AutoPullResponseHandler's    public synchronized CompletionStage<Record> nextAsync() {

can cause choking to the enqueueing of records. Both enqueueing and dequeueing use (and lock) the same AutoPullResponseHandler  instance, but this lock on this method appears premature since there might not be any records on the queue yet, and locking will mean they can't be added. (I could be wrong :)

**Comment by owaincole** [comment]
Oh, and did you test with autocommit turned off :)
 
See BoltNeo4jUtils 
  public static <R> R executeInTx(BoltNeo4jConnection connection,
                                    String sql,
                                    Map<String, Object> params,
                                    Function<Result, R> body) throws SQLException {
        try {
            Result statementResult = execute(connection, sql, params);
            R result = body.apply(statementResult);
            if (connection.getAutoCommit()) {
       //         connection.doCommit();		// CANT DO THIS HERE BECAUSE (async) RESULTS NOT CONSUMED YET!!!
                System.out.println("auto commit commented out");
            }
            return result;
        }  catch (Exception e) {

**Comment by dam-mond** [comment]
@conker84 Customer tested the fix you created, it appears that the memory issue previously reported has been fixed.
However, there appears to be another performance issue after the fix, here's the customer feedback:

> The parallel behaviour which is now newly exposed (since previous the driver fully populated the queue from the database before allowing it to be read) requires both the thread writing the data from the database into the queue, and the thread reading it from the queue to 'play nicely'.
I'm a bit unclear as to exactly why, but in my local testing (using a remote database on a server, and not really doing anything with the results), then this performs a lot slower, with the queue often being empty. It's about twice as slow. I.e. it appears that either the reader thread isn't playing nicely, or there's something about how the AutoPullResponseHandler is handling when the queue is practically empty.

**Comment by conker84** [comment]
Sorry really don't get what the user is complaining for.

**Comment by owaincole** [comment]
Hi @conker84 . It's not an issue with your jdbc drivers. I'm very happy with the fix you have made. 
(The AutoPullResponseHandler is in neo4j-java-driver jar. Which is neo4j product.)

If you could indulge me, could you run a quick (performance) test on a remote database (i.e. one that has a little latency on the connection). e.g. just run
```
public void fetchSomeNodes() {
		
		long t=System.currentTimeMillis(); // time at start
		List results=jdbcTemplate.queryForList("match (n) return n limit 10000");
		long timeTaken= System.currentTimeMillis()-t;
		System.out.println(" Result from start -->"+results.size()+" in "+timeTaken+" ms "+(timeTaken/1000)+" secs");
		
	}
```
Firstly using a connection that is going to grab all the results (old behaviour) e.g. by turning on AutoCommit. And then the same with your new behaviour. I've put mine in a loop and run that 5 times. I'm getting the old behaviour is faster (on average) by several seconds:

```Iteration 0
Fetching Some nodes Async  <-- THIS IS NEW BEHAVIOUR
 Result from start -->10000 in 23588 ms 23 secs
Fetching Some nodes Not Async <-- OLD BEHAVIOUR
 Result from start -->10000 in 15455 ms 15 secs
...... 
```

Anyway, if you don't see this behaviour, then I'll assume it's something wrong with my test setup :) 

 (Note I know that shoving all the results in a list rather negates the point of loading them asynchronously: we normally use a rowhandler :) But I was trying to boil down the test to the simplest form)

**Comment by conker84** [comment]
I see that you're referring to `jdbcTemplate` which I assume is Spring's JdbcTemplate right?

**Comment by owaincole** [comment]
Yes. We're using spring's jdbc transaction control etc. We've found it works very well with your driver. But you can test with any jdbc connection type. I'm hoping you dont find any timing difference, and it's a problem with my test setup...

**Comment by conker84** [comment]
@owaincole Can you please provide a flame graph of the execution of the two different use-cases?

**Comment by conker84** [comment]
You can use this tool:

https://github.com/jvm-profiling-tools/async-profiler

**Comment by owaincole** [comment]
Hi, bit tricky as we're using PCs (that tool only supports linux/mac) and Temurin JVM due to corporate licencing agreements which looks like it's incompatible with most profiling tools. I'll keep digging. Did you profile your test run?

**Comment by owaincole** [comment]
I've still had no luck at getting a decent profiler output. 
Can I just ask when the jdbc driver is likely to be released with the current fix in it?
It's quite an important one because we're finding that multiple large queries are eating all the memory in our server :(
