### ISSUE TITLE
Test with DBVizualizer

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#4]

**Comment by sim51** [comment]
# Step 1: Driver
- Menu `Tools > Driver Manager`
- Menu `Driver > Create Driver`
- Give a Name to the diver
- On the `User Speicified` panel, click on the folder icon to add the Neo4j JDBC Jar
- `org.neo4j.jdbc.Driver` should now be selected into **Driver Class** list
- On the **URL Format**  put the jdbc bolt or http URL : `jdbc:bolt://localhost/?noSsl` or `jdbc:http://localhost`
- Create a database connection with the wizard
- Give a name, for example `Neo4j`
- Select Database Driver : `Cache`
- Click on `Load Driver File(s)` and go where you have saved the Neo4j JDBC jar

# Step 2: Create database connection
- Create a new **Database Connection** with the wizard
- Give a name to this connection
- On the next screen, select the **Driver** that you have created at Step 0
- fulfill the form like this 
- **Database Url** : the jdbc bolt or http URL : `jdbc:bolt://localhost/?noSsl` or `jdbc:http://localhost`
- **Database Userid :** `neo4j`
- **Database password:** the one of your database

# Step 3 : Query
- Open a new **SQL Commander** with `CTRL+T`
- Create your query, for example `MATCH (n) RETURN n LIMIT 100`
- Execute your query with `CTRL+ENTER' (click on Connect and execute if needed)

![dbvis](https://cloud.githubusercontent.com/assets/231657/15807733/a00cef5e-2b65-11e6-97d0-6e4364113271.png)
