### ISSUE TITLE
support https

### ISSUE THREAD

**Issue by jexp** [neo4j/neo4j-jdbc#45]

**Comment by sim51** [comment]
# Importing Neo4j certificat to your JVM
- Open your browser on this : https://localhost:7473
- Export the certificat as a binary DER and save it on your filesystem (for example: /tmp/neo4j-cert.der)
- Execute this command  (replace @JAVA_HOME@ with your JVM location) : 

```
$> cd @JAVA_HOME@/jre/
$>  bin/keytool -import -alias neo4j -keystore @JAVA_HOME@/jre/lib/security/cacerts -file /tmp/neo4j-cert.der
```
