### ISSUE TITLE
debug mode

### ISSUE THREAD

**Issue by sim51** [neo4j/neo4j-jdbc#46]
Debug mode was removed in RC1, because we were using mockito, and we don't want to have a test library into the package.

This is a list of solution: 
1. **Cglib** : work is already done with a few code modification, but Cglib is common lib so we should discovered libs conflicts with some products
2. **Javassist** : Same as cglib for conflicts
3. **Java proxy class** : It's possible to use native java proxy class, but to implement it, we need to make some code modification (ie. using interface into InstanceFactory.debug, with all impacts needed)
4. **Using p6spy** : P6spy makes a proxy class but only  on a little number of class (Connection, Statement, PreparedStatement and CallableStatement) , and on each proxy class, they log only a little number of methods (commit, rollback, execute). So it's a good start, but it's not enough to debug the driver
5. Implement logger when we needed into the code with java logger interface or slf4j

My preference go to 3 or 5, and I prefer 3 to have something generic.

What do you think ?

**Comment by jexp** [comment]
I would also vote for 4. to start with (or as recommendation for users) 
And then 3.

Not sure how important the full logging is? For development debugging it might be easier, then you have also access to all the private internal state.

**Comment by inserpio** [comment]
In a past project where I was asked to debug the oracle driver, I wrapped it just like we are wrapping the java-bolt driver in this jdbc one. We could create an external project and people could decide to use neo4j-jdbc-driver-3.0.jar or neo4j-jdbc-driver-debug-3.0.jar 

Here you can read about the oracle _g jar with log -> http://www.rgagnon.com/javadetails/java-0663.html

**Comment by mvitz** [comment]
If 1) would be an easy alternative the maven-shade-plugin is capable of changing the packets (see https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html) then cglib wouldn't conflict with any other library. The only problem that could come is that on a newer java version this driver would only be usable after a new version of cglib is provided.

**Comment by jexp** [comment]
What's the last status on this? Is there any low key thing that we can do?

**Comment by sim51** [comment]
The last status is that debug mode do nothing for now, so we are using p6spy.
In a future version, we have to implement the point 4 (ie. using Java proxy class).

**Comment by glaggia-larus** [comment]
I've opened a pull request for this. We are trying to insert it into the next release
