### ISSUE TITLE
Virtual column for bolt on node & relationship

### ISSUE THREAD

**Issue by sim51** [neo4j/neo4j-jdbc#48]
Compute virtual column for nodes & relations can't be correctly implemented on a JDBC driver, because  we will need to make a full scan on the result to compute the list of all column available (a result is a collection of static tuples). 

For example if you make this query on the Movie graph `MATCH (n)-[r]->(m) RETURN n,r,m` you will have on `n` some `Movie` & `Person` nodes, that haven't the same properties (it's the same for m & r).

Moreover, because Neo4j is schemaless, two `Movie` nodes can have different properties. So it's impossible to compute the ResultSet column, without to make a result full scan before.

From my POV, on complexe object, we need to return an Object : we can cast `InternalNode`, `InternalRelationship` & `InternalPath` to a POJO.

(it's related to #43).

**Comment by albertodeste** [comment]
The issue you're referring to is related to a specific request for the Bolt Driver asked at the beginning stages. I think that in the specific situation you're describing (node - aka column in this case - with multiple types) could be partially solved with a sampling approach as Michael many times suggested to me. About the POJO for complex objects the idea was about returning a JSON (as it actually is or should be) for having both a readable result (for graphical tools) and something that can be imported as an Object.

**Comment by sim51** [comment]
1) Like you said, a sampling approach will solve some cases, but not all of them ... 
Moreover, with this solution, you can execute the same query two times, and not to have the same result (ie. same columns).

2) For complex object, the driver return a Map, so it's perfect.

**Comment by jexp** [comment]
It is intentional for tools that can't deal with Map objects.

And I think the sampling etc. is fine as long as we can get it to work.

**Comment by jexp** [comment]
Decision:
- make it a connection parameter: `flatten=sampleRows` , where sampleRow is the number of rows that are sampled to figure out the columns, if -1 then sample all rows
- by default switched off

**Comment by albertodeste** [comment]
Implemented

**Comment by jexp** [comment]
Good job, works well!
