### ISSUE TITLE
ResultSetMetaData.getTableName not implemented

### ISSUE THREAD

**Issue by ralfbecher** [neo4j/neo4j-jdbc#49]
java.lang.UnsupportedOperationException: Method getTableName in class org.neo4j.
jdbc.ResultSetMetaData is not yet implemented.
        at org.neo4j.jdbc.utils.ExceptionBuilder.buildUnsupportedOperationException(ExceptionBuilder.java:41)
        at org.neo4j.jdbc.ResultSetMetaData.getTableName(ResultSetMetaData.java:166)

Could return a tablename like "CypherQuery" or else

**Comment by sim51** [comment]
It's already implemented into master branch : https://github.com/neo4j-contrib/neo4j-jdbc/blob/master/neo4j-jdbc/src/main/java/org/neo4j/jdbc/ResultSetMetaData.java#L152-L154

From specification, returned an empty string is equal to  'not applicable'.
