### ISSUE TITLE
ResultSet#close cannot be called multiple times

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#51]
Instead, an exception will be thrown if called when it's already closed.
Therefore, the following code used to work with the legacy JDBC driver, won't work now:

``` java
try (Statement statement = connection.createStatement();
    ResultSet resultSet = statement.executeQuery(query)) {
    // do something with resultset
}
```

`Statement` closes `ResultSet` first and `ResultSet` explicit close will fail.

**Comment by glaggia-larus** [comment]
@fbiville I assume that you are referring at the HTTP module, can you confirm?

In that case I agree in what you said, as stated in the specifications for that method "Calling the method close on a ResultSet object that is already closed is a no-op."

I didn't see any problem with the BOLT module though.

**Comment by fbiville** [comment]
Sorry for the late reply. Yes, it occurred when I used the HTTP module.

**Comment by glaggia-larus** [comment]
I've updated the jar in the release section, can you please check if the problem is solved?
