### ISSUE TITLE
Improve HTTP driver URL validation error message

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#52]
The error message when the JDBC connection string is not correct is weirdly phrased:

```
Caused by: java.sql.SQLException: JDBC url is not bad
    at org.neo4j.jdbc.http.HttpDriver.connect(HttpDriver.java:59)
    at java.sql.DriverManager.getConnection(DriverManager.java:664)
    at java.sql.DriverManager.getConnection(DriverManager.java:247)
```

Best would be to give a few examples of correct connection strings.

**Comment by glaggia-larus** [comment]
I agree in changing that message, however I personally don't like to put instructions in exceptions' messages.
For this reason I label this as a bug for now, if we decide to enhance that message I will mark it also as an "enhancement"

**Comment by jexp** [comment]
@glaggia-larus Actually there is an API design book that advocates adding the information to exception messages that helps users make the exception to go away. 

Our drivers team adopted that for our drivers, so if we can do the same I'd be for it.

**Comment by glaggia-larus** [comment]
Perfect, I've added the enhancement label. I don't know if I will be able to look at this today, in case I'll do, I will assigne this to me.

**Comment by glaggia-larus** [comment]
Now the exception returns:

```
JDBC URL is not correct.
A valid URL format is: 'jdbc:neo4j:http://<host>:<port>'
```

**Comment by wangjunting** [comment]
glaggia-larus，Do you resolve this problem yet?

**Comment by glaggia-larus** [comment]
The issue was closed and the the exception now returns an example, as asked.
