### ISSUE TITLE
In memory db with JDBC

### ISSUE THREAD

**Issue by psilons** [neo4j/neo4j-jdbc#53]
It seems that with the new JDBC driver for Neo4j 3.0.x, the in memory database is not working: 
jdbc:neo4j:mem:mydb
jdbc:neo4j:file:/home/user/neo/graph.db
as described in https://github.com/neo4j-contrib/neo4j-jdbc-2x.

Is there any plan to support these? They are very convenient for unit/integration testing.

Thanks

**Comment by mvitz** [comment]
I planned implementing this and had a look at the old implementation  but didn't have enough time till now doing it ;-)

**Comment by psilons** [comment]
Thanks a lot, Michael. Really appreciate it.

**Comment by justinwyer** [comment]
Any movement on this, it's a huge missing feature.

**Comment by mvitz** [comment]
Sorry, currently my time is very limited. The last version can be seen at https://github.com/mvitz/neo4j-jdbc/tree/embedded-mode

**Comment by sharath1608** [comment]
I'm waiting on the edge for this. Cannot move back to 2.x so I'm currently relying on GraphDatabaseFactory to connect to in-memory db. Any progress so far on this?
