### ISSUE TITLE
Deploy RC and Snapshots to Maven Repository

### ISSUE THREAD

**Issue by mvitz** [neo4j/neo4j-jdbc#55]
It seems that currently wether the RC nor any Snapshot is deployed into any public accessible Maven Repository. Is it possible to change this? Maybe now since these is an "official" Neo4j project it's possible to use the neo4j-repo?

**Comment by jexp** [comment]
You mean like this?

https://m2.neo4j.org/content/repositories/releases/org/neo4j/neo4j-jdbc-driver/3.0-RC1/

There is also https://jitpack.io/ which seems to be a cool way of treating GH releases as Maven repos.

**Comment by mvitz** [comment]
Argh I looked at snapshots and into staging ;-) Thanks for pointing out the obvious.

jitpack.io may be cool but isn't an option for me. I like relying on stable release stuff not on changing git repos ;-)
