### ISSUE TITLE
JDBC Driver for Solr?

### ISSUE THREAD

**Issue by mattfiocca** [neo4j/neo4j-jdbc#56]
Hello,

I have absolutely zero experience working with .jar files and java as a whole, but what i'm looking to do is see if I can use this as a jdbc driver for Apache Solr (v6.1.0). 

In the xml configurations for Solr, it lets me specify a jdbc driver (.jar) as the connection driver to our data store (Neo4j in our case). In your docs, you say "Add the JDBC driver jar file to your project", but I am unclear which jar file from this project I should be grabbing, or do i need to download the whole project and compile this in someway producing a final .jar archive? 

Any advice on how to get rolling will be much appreciated.

**Comment by freeeve** [comment]
You can get the jar file here: https://github.com/neo4j-contrib/neo4j-jdbc/releases

You want to drop it in your solr/lib folder, then use it like you would any jdbc driver in your data import handler, etc.--define your entities, define your cypher queries, and use the connection URL like it is defined in the readme. We managed to migrate our solr data import handler from Oracle to Neo4j in an afternoon thanks to this handy driver.

**Comment by inserpio** [comment]
@glaggia-larus, all, it would be nice to have add solr among the tested tools (with an example and some screenshots), no?

**Comment by freeeve** [comment]
My colleague today corrected me saying there is a special lib folder for data import handlers, it's not the root Solr lib. At least in version 5.4 that we are using.

**Comment by mattfiocca** [comment]
awesome guys!

I'm working this into my solr setup now. Thanks for your guidance.

**Comment by mattfiocca** [comment]
For what its worth,

Our neo-solr data import handler is working like a champ!

My only beef is in not knowing how to do the delta queries in Solr given the last index date is stored as a date string Solr-side, making it difficult to compared this date with our unix timestamp long integers representing our modified dates in our neo data. So, we are handling indexing of incremental saves/deletions application side. This tool is awesome for doing mass full-imports though.

Thanks team!

p.s. If anyone has insight on the delta queries in Solr for incremental indexing based on last_index_date, i'm all ears!

**Comment by Sankitha** [comment]
Hi, 
Is there any way that I can import the json data generated by solr to neo4j?

Thanks in advance:)

**Comment by jexp** [comment]
@Sankitha can you provide an example?

**Comment by inserpio** [comment]
@Sankitha you could invoke the apoc.load.json procedure via neo4j-jdbc.

**Comment by Sankitha** [comment]
@jexp I have an output as json file from Solr . I want it to be pushed to neo4j for more Analyses. My concern is about how to I bridge between Solr and Neo4j to achive this functionality.
@inserpio can you please share me some documents regarding using apoc.load.json.

**Comment by jexp** [comment]
see here for load json: https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_load_json

Which is also what we use for the ES integration internally.

**Comment by Sankitha** [comment]
even after using apoc plugin while loading json I am getting error 
Query cannot conclude with WITH (must be RETURN or an update clause) (line 1, column 1 (offset: 0))

"WITH "https://api.stackexchange.com/2.2/questions?pagesize=100&order=desc&sort=creation&tagged=neo4j&site=stackoverflow&filter=!5-i6Zw8Y)4W7vpy91PMYsKM-k9yzEsSC1_Uxlf" AS url"

**Comment by Sankitha** [comment]
I could able to resolve this with 
WITH "https://api.stackexchange.com/2.2/questions?pagesize=100&order=desc&sort=creation&tagged=neo4j&site=stackoverflow&filter=!5-i6Zw8Y)4W7vpy91PMYsKM-k9yzEsSC1_Uxlf" AS url

CALL apoc.load.json(url) YIELD value

UNWIND value.items AS item

RETURN item.title, item.owner, item.creation_date, keys(item)


Thanks @jexp and @inserpio
