### ISSUE TITLE
Exception: java.lang.UnsupportedOperationException: Method isValid in class org.neo4j.jdbc.Connection is not yet implemented.

### ISSUE THREAD

**Issue by rgjamkhedkar** [neo4j/neo4j-jdbc#64]
Getting this exception when using Driver with Scalikejdbc.

**Comment by inserpio** [comment]
Hi Rohan, I confirm you the method is still not yet implemented as many other ones regarding meta-data, because we don't know exactly which ones are used by every tool and implementing all of them was too hard for Rel. 1.0.

We're going to prepare a patch for you asap.

Cheers,
Lorenzo

**Comment by glaggia-larus** [comment]
This should be fixed for BOLT module with c7acc09

A new snapshot version jar is available here: https://github.com/neo4j-contrib/neo4j-jdbc/releases/download/3.0.1-SNAPSHOT/neo4j-jdbc-driver-3.0.1-SNAPSHOT.jar

Can you please try it out and give us a feedback?

**Comment by jasperdenkers** [comment]
Confirmed this resolved the issue for me, see https://github.com/neo4j-contrib/neo4j-jdbc/issues/65#issuecomment-234482085.

**Comment by glaggia-larus** [comment]
Closed, 

thank you for your help in report this issue, feel free to open other issues if needed.

Cheers
