### ISSUE TITLE
Sql Workbench/J requires reconnection when any error in the query occurs

### ISSUE THREAD

**Issue by slavakx** [neo4j/neo4j-jdbc#66]
I get the following error message every time when I run a query the second time when the first time the query contained any error:

N/A: Cannot run more statements in this transaction, because previous statements in the transaction has failed and the transaction has been rolled back. Please start a new transaction to run another statement.

When no errors are in the query it runs ok.

**Comment by sim51** [comment]
Hi

Thanks for reporting this bug.

Can you respond to those questions :
- Are you on autocommit mode ?
- Can you give us your url connection ?

Cheers

**Comment by slavakx** [comment]
Hi

The autocommit was the issue. It was off. It works fine with autocommit on. 
Thanks!
