### ISSUE TITLE
using RJDBC in R fails because of unimplemented ResultSet class in org.neo4j.jdbc

### ISSUE THREAD

**Issue by slavakx** [neo4j/neo4j-jdbc#67]
I am trying to connect to Neo4j from R (I am aware of RNeo4j library though)

I get the following exception:

Method setFetchSize in class org.neo4j.jdbc.ResultSet is not yet implemented.

I manage to get a result object in <JDBCResult> but I cannot iterate through it. 

My connection string is the following: jdbc:neo4j:bolt://localhost?noSsl,debug=true,flatten=[-1,100,1000])

**Comment by inserpio** [comment]
Hi @slavakx, we're working on the issue. Method `setFetchSize` is indeed not yet implemented and we need to decide how to implement it.

In the meantime Please pay attention to the `flatten` param: you should provide a value. That list was just meant to give an example of possible values. Please have a look at this: https://github.com/neo4j-contrib/neo4j-jdbc#flattening

Connection URL could be something like this:
`jdbc:neo4j:bolt://localhost?noSsl,debug=true,flatten=100`

**Comment by inserpio** [comment]
Hi @slavakx, could you please retry with this snapshot version? https://github.com/neo4j-contrib/neo4j-jdbc/releases/download/3.0.1-SNAPSHOT/neo4j-jdbc-driver-3.0.1-SNAPSHOT.jar

I just added a basic implementation for the missing method.

Let me know if it solves the issue.

**Comment by slavakx** [comment]
Hi @inserpio 

The snapshot works fine!

Just out of curiosity - how was it working in the 3rd party tool like SQL Workbench/J with the unimplemented ResultSet ?

Best

**Comment by inserpio** [comment]
Cool! I'm closing this issue then..

We currently haven't implemented the entire JDBC interface mainly for two reasons:
1. we rather wanted to fail than causing unexpected behaviour (cit. @jexp)
2. we favoured to go live with a minimal marketable set of features 

Just as an example the `DatabaseMetadata` interface declares 176 methods and it sounded ways too long to fully implements it in the first release: we wanted you to benefit of the new BOLT protocol ASAP :-)

Core classes and methods (i.e. ResultSet) are of course implemented and as soon as we understand that some (not yet implemented) methods are required by some tools we start woking on it. 

Thanks for helping us.
