### ISSUE TITLE
`SELECT DISTINCT` Translation in SQL to Cypher

### ISSUE THREAD

**Issue by bonelli** [neo4j/neo4j-jdbc#674]
The current version 6.0.0-M04 of the SQL to Cypher translator does not handle the SELECT DISTINCT statement as I would expect. I am curious if this could be addressed in a future roadmap.

Here is a real-life example.

The SQL statement:
```
select distinct "NAME" from "Pgm" where "snapshotId" = ?
```
is translated to:
```
MATCH (pgm:Pgm) WHERE pgm.snapshotId = $1 RETURN pgm.NAME
```

In this case, I believe the SQL DISTINCT keyword could be directly translated to RETURN DISTINCT in Cypher.

Thank you

**Comment by michael-simons** [comment]
Great catch from your side, oversight from ours. Thank you!
