### ISSUE TITLE
README: Correct artifact name is 'neo4j-jdbc-driver'

### ISSUE THREAD

**Issue by tommystanton** [neo4j/neo4j-jdbc#72]
In the README, the artifact of the dependency in the examples is `neo4j-jdbc`, but in order for those examples to compile, the artifact actually needs to be `neo4j-jdbc-driver`.

In my experience, if the artifact was simply `neo4j-jdbc`, I would eventually run into this sort of exception at run-time:

``` text
java.sql.SQLException: No suitable driver found for jdbc:neo4j:bolt://localhost
```

...and I believe that that is because a class named `Driver` is not found (a requirement of the classpath when using JDBC).  `Driver` is only in the `neo4j-jdbc-driver` artifact.

**Comment by fpavageau** [comment]
I started working on this a few hours before you opened the issue, as a matter of fact. I hope to open a pull request today.

**Comment by michaelahlers** [comment]
I've got this same issue regardless which artifact (`neo4j-jdbc` or `neo4j-jdbc-driver`) I use in my project. (Any chance this is related to neo4j/neo4j#8832, where required classes can't load because of incompatibilities between Scala versions?)
