### ISSUE TITLE
Old versions of neo4j-jdbc removed from the Maven repository?

### ISSUE THREAD

**Issue by tommystanton** [neo4j/neo4j-jdbc#73]
Was just curious as to whether removal of old versions was intentional.

A [search on the Maven repository](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22neo4j-jdbc-driver%22) shows that only version `3.0` is available.

I assume that older versions were once available, given that other projects [1] [2] are pointing to version `2.x` of artifact `neo4j-jdbc-driver`.

[1] `luanne/flavorwockyGraphUnit`
[2] `neo4j-examples/movies-java-spring-boot-jdbc`, until recently

**Comment by fpavageau** [comment]
The legacy driver (now hosted under https://github.com/neo4j-contrib/neo4j-jdbc-2x) used "neo4j-jdbc" as the artifact name and was never published on Maven Central, only on the [Neo4j repository](https://m2.neo4j.org/content/repositories/releases/org/neo4j/neo4j-jdbc/).

I don't think anything was removed from Maven Central, this is not left-pad 😄 .

**Comment by inserpio** [comment]
Just add the above mentioned Neo4j repository in your pom file if you need to use previous to 3.0 versions. Example here: http://dist.neo4j.org/settings.xml
