### ISSUE TITLE
Feature: Make LLM in translator configurable

### ISSUE THREAD

**Issue by anming81** [neo4j/neo4j-jdbc#759]
`var model = OpenAiChatModel.builder().modelName("gpt-4-turbo").temperature(0.0).apiKey(openAIApiKey).build();`

Add configuration items such as baseUrl and modelName, we can work with openai api compatible llms too.

**Comment by michael-simons** [comment]
Hey, thanks for trying this out!

For starters, I would suggest adding the model name, temperature and base url via standard JDBC properties.

**Comment by michael-simons** [comment]
This has been implemented by @meistermeier in 3e91638 and will be in the next patch release.
