### ISSUE TITLE
How can we import data in chunks using transactions?

### ISSUE THREAD

**Issue by maxdemarzi** [neo4j/neo4j-jdbc#77]
Currently taking about 10 minutes to import 7000 records via Pentaho following the example since it's writing one record at a time. Is there a way to bunch up the writes in chunks of 100/1000/etc per transaction?

**Comment by inserpio** [comment]
`Execute row sql script` allows to specify commit interval. Here's the documentation: http://wiki.pentaho.com/display/EAI/Execute+row+SQL+script
I'll test it and give you a feedback soon.
Also `Notes` in `Execute sql script` (http://wiki.pentaho.com/display/EAI/Execute+SQL+script) clearly states that this option is not performant at all.
I'll also review the documentation.

**Comment by michael-simons** [comment]
Version 6 does rewrite batched prepared SQL statements into Cypher unwinds by default.
Otherwise this is a question specific to a product which does not exists in the form of 2016 anymore. Happy to reopen this if it becomes relevant again.
