### ISSUE TITLE
Document how to mock a neo4j database for neo4j-jdbc

### ISSUE THREAD

**Issue by ikus060** [neo4j/neo4j-jdbc#80]
Would be nice to properly describe how to mock a neo4j database to make it work with neo4j-jdbc. I'm struggling to make this work. There are too much information about how to do it for neo4j v2.

In other word, may you describe how to properly create a neo4j database usable in application testcases and make use of it using ne4j-jdbc ?

Thanks

**Comment by inserpio** [comment]
You could refer to unit tests like one [BoltConnectionTest](https://github.com/neo4j-contrib/neo4j-jdbc/blob/master/neo4j-jdbc-bolt/src/test/java/org/neo4j/jdbc/bolt/BoltConnectionTest.java).

**Comment by mvitz** [comment]
I started an embedded driver for 3.x a while ago and just pushed it to https://github.com/mvitz/neo4j-jdbc/tree/embedded-mode
Maybe this helps someone who has more time.

**Comment by inserpio** [comment]
@mvitz  Hi Michael, thanks fof that. Now that 3.0.1 is out, we're planning for a 3.1 eventually introducing embedded and/or file mode. In case we decide to go with this we'll surely take advantage of this your contrib. Thanks again.

**Comment by glaggia-larus** [comment]
This issue refers to #53 that is being worked to be merged in the new 3.2 release.
