### ISSUE TITLE
Update POM with the latest dependencies

### ISSUE THREAD

**Issue by anuragsrivastava06** [neo4j/neo4j-jdbc#82]

**Comment by inserpio** [comment]
Which ones are you referring to in particular @anuragknoldus? Should be coherent with our current  tests and plans

**Comment by anuragsrivastava06** [comment]
I have updated dependency version for powermock, junit, org.openjdk.jmh, neo4j-kernel, neo4j-harness and jackson. 

I have sent PR also. You can refer that.

**Comment by inserpio** [comment]
Just seen it. I'll have a look at it.
In the meantime could you please share with us your particular use case (if any).
We'd like to know how people are using the driver in order to better support you.

**Comment by anuragsrivastava06** [comment]
I am exploring Neo4j with Scala and in this process I started using Neo4j-jdbc and found Bolt and it looks so cool. I am just exploring it.

**Comment by inserpio** [comment]
3.0 and 3.1 branches now have the latest ones.
