### ISSUE TITLE
java.lang.UnsupportedOperationException: Method supportsCatalogsInIndexDefinitions in class org.neo4j.jdbc.DatabaseMetaData is not yet implemented.

### ISSUE THREAD

**Issue by fhureau** [neo4j/neo4j-jdbc#84]
I am trying to connect to a Neo4j 3.0.4 Community standalone server from a project in Talend Open Studio using Talend Framework via the 3.0.1 jdbc driver, but when I want to finish configuring the connection I get the following error message:

Failed to access data {0} java.lang.UnsupportedOperationException: Method supportsCatalogsInIndexDefinitions in class org.neo4j.jdbc.DatabaseMetaData is not yet implemented.

Any idea about where this could come from?

Thanks

**Comment by inserpio** [comment]
Yes, we know that. It's a matter of unimplemented methods. Not all DatabaseMetaData and ResultSetMetaData methods are implemented as they're plenty and we really don't know which are effectively used by tools.
We can add it to the outcoming 3.0.2.

**Comment by inserpio** [comment]
The implementation is just a simple `return false`  as there's no `catalog` in neo4j.
Other methods may be required as soon as we add it...
We don't know which ones are called by Talend: lust let us to set up a test env to simulate the problem.

**Comment by fhureau** [comment]
Ok thanks. Yes that would be great please. I just hope it will not throw me another one after that ^^

**Comment by fhureau** [comment]
Ok thanks!
