### ISSUE TITLE
SQLException thrown on invalid jdbc URL

### ISSUE THREAD

**Issue by chillinger** [neo4j/neo4j-jdbc#87]
If multiple JDBC Drivers are loaded and a call to `java.sql.DriverManager` is made with a non-neo4j URL, the connect method throws an `java.sql.SQLException` regarding the incorrect URL.
It actually should only return `null`, the `DriverManager` then tries the next available JDBC driver or throws an Exception if no connection was established.

How to reproduce:

load the neo4j JDBC driver and MySQL Connector/J  and try to connect to a mysql URL.

Current workaround:

Before calling the DriverManager for a new connection, deregister the neo4j driver, afterwards re-register it.

**Comment by glaggia-larus** [comment]
Hello, thank you for reporting this to us.

I was checking in the documentation why we decided to throw an exception in first place. We considered what **for us** is a 'bad' URL as an error, of course we did not take in account the simultaneous use of our driver with another one.

I think we will be able to check on this as soon as possible. Let us discuss this issue with the team to decide how to procede.

Have a nice day
