### ISSUE TITLE
Allow TrustStrategy to be configured through JDBC driver

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#88]
I was trying to use the Bolt JDBC driver the other day in unit tests, but it failed because of the default trust strategy:

```
Caused by: java.security.cert.CertificateException: Unable to connect to neo4j at `localhost:7687`, because the certificate the server uses has changed. This is a security feature to protect against man-in-the-middle attacks.
If you trust the certificate the server uses now, simply remove the line that starts with `localhost:7687` in the file `/Users/f.biville/.neo4j/known_hosts`
```

It seems this can be configured with the Java Bolt driver, as follows:

> From 1.1.0 version `private TrustStrategy trustStrategy = trustAllCertificates();` is enabled by default. Prior 1.1.0 it was `TRUST_ON_FIRST_USE`

In my opinion, it would be nice to allow this strategy to be configured through the JDBC driver. It's true, though, that simply upgrading to 1.1.0 would do the trick in my case.

**Comment by jexp** [comment]
I think this should happen through properties,
if you have time, could you send a PR for this?

**Comment by fbiville** [comment]
I cannot promise any ETA but I can try to work on this.

**Comment by glaggia-larus** [comment]
I have done this, I'm waiting for the refactor PR to be merged to create this PR.
