### ISSUE TITLE
Neo4j 2.x support

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#89]
JDBC has been the way to go for libraries that need to support Neo4j various connectivity modes.
Currently, for https://github.com/fbiville/liquigraph/, we have to maintain two distinct branches of development:

- one for Neo4j 2.x with a fork of the legacy JDBC driver
- one for Neo4j 3.x with the new driver

I believe this makes maintainer's life difficult and it may slow down the JDBC driver adoption as well. People still have Neo4j 2.x in production and could benefit from trying the new JDBC driver in a stable environment before using against an upgraded Neo4j 3.x version.

I know this requires a lot of efforts, but I'm pretty sure the core of the JDBC driver contains most of the logic needed to support HTTP/embedded 2.x.

I can lend a hand in developing this, although my time, as anyone's, is rather limited.
WDYT? Do you foresee any major problems trying this?

**Comment by jexp** [comment]
@fbiville http should work out of the box, or?

embedded is more tricky, we could try two things 1. if the 3.x code still compiles on 2.x then just release it also build for 2.x 
if it doesn't work we'd have to copy the code or extract a common parent module that keeps the "common" code across the versions. That's def. more effort.

**Comment by fbiville** [comment]
@jexp I started the latter approach a while ago (for both embedded and http, maybe not needed as HTTP as you suggest, need to test this), it's definitely feasible.

I'd like to make some time to work on this as that would greatly simplify Liquigraph development. If someone from the team is available to hold (possibly remote) pair-programming sessions, that'd be great!

**Comment by fbiville** [comment]
As briefly mentioned on Neo4j-Users.slack.com, https://github.com/liquigraph/trinity tries to solve this issue (still very alpha) and it supports:

- HTTP (Neo4j 2/3)
- Embedded (Neo4j 2/3)
- Bolt (missing bolt+routing perhaps?)

There are some API refinements and performance analysis to carry out, but it would bring Neo4j 2 support out of the box.

**Comment by fbiville** [comment]
3.5 is the active LTS version, 2.x should not be used by anyone.
