### ISSUE TITLE
Implement DataSource

### ISSUE THREAD

**Issue by fbiville** [neo4j/neo4j-jdbc#90]
Hi, 

On Liquigraph side, we just introduced a new Spring Boot starter module.
Users have to pull an extra dependency (so far, we've used `HikariCP` in our examples) or come with their own datasource implementation for the starter to work, which is a pity.

Given all the other JDBC APIs are implemented, could it be possible to implement `DataSource` as well?
That way, just depending on `liquigraph-spring-boot-starter` would be enough to get the migrations up and running.

**Comment by glaggia-larus** [comment]
Thank you for asking us this.

I think we will look at this problem as soon as possible.

**Comment by glaggia-larus** [comment]
I've opened a new PR.
@fbiville can you please check if this implementation is ok with your software?

- Added DataSource implementation
- Added Unit tests
- Added an Integration Test

You can configure the DataSource using BoltNeo4jDataSource methods such as:
- setServername (defautl = localhost)
- setPortNumber (default = 0 - when lte 0 not added to the URL)
- setUser
- setPassword
- setIsSsl (default = false)

Let me know
