### ISSUE TITLE
Problems because of shaded artefacts

### ISSUE THREAD

**Issue by mvitz** [neo4j/neo4j-jdbc#91]
During working on an example app to show how to connect Liquigraph and Spring Boot I found https://github.com/fbiville/liquigraph-spring-boot-example/issues/4

It seems that some component in this application is not able to work with `jackson:2.7.0` which the shaded `neo4j-jdbc-http`-Driver includes. (btw. Spring-Boot uses `2.8.5` as default Jackson version).

I understand that the `neo4j-jdbc-driver` is shaded for easier tool usage. But why need the finer-grained drivers shading as well? If there is no way out of shading you should at least relocate these classes as described in https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html. However keep in mind that shading (even without relocating) may already violate some  licenses of dependencies you are using.

**Comment by sim51** [comment]
Hi @mvitz 

A good compromise could be to only shade the `neo4j-jdbc-driver` and not the others.
So later, your project should works if you make a dep to a specific driver (like `neo4j-jdbc-http` or `neo4j-jdbc-bolt`), and we also keep the easy of use for tools.

What do you think ?

Cheers

**Comment by mvitz** [comment]
This compromise would be suitable for me and seems to be the best solution for the time being without affecting to much users.

**Comment by jexp** [comment]
I think it's a different use-case
1. using jdbc with a tool (which often only allows for a single jar) -> shadow at least http and bolt
2. using jdbc in a program -> it should probably not shadow or shadow bolt by default for easier setup

so perhpas we can create different artifacts
1. a full shadow for bolt + http for use in a tool
2. non-shadowed versions where you would explicitely put in http or bolt and they would pull their dependencies via maven
3. optionally a small version of just bolt embedded

**Comment by mvitz** [comment]
d188b9a4a419c36345cd33cc6973c59a31f90cb7 fulfills 1. and 2. of your list.

**Comment by inserpio** [comment]
@jexp we currently have both `neo4j-jdbc-bolt-3.x.x.jar` and `neo4j-jdbc-http-3.2.0.jar` not shaded and `neo4j-jdbc-driver-3.x.x.jar` shaded. Should we close this?

**Comment by glaggia-larus** [comment]
As it is done, I close this.

There is a similar problem with the new embedded version.
