### ISSUE TITLE
Bolt JDBC driver gives error as "Failed to establish connection with server. Make sure that you have a server with bolt enabled on localhost:7687"

### ISSUE THREAD

**Issue by AbhayParab** [neo4j/neo4j-jdbc#94]
Hi

I have written following code similar to one mentioned as below:

        try (Connection connection = neoConnection()) {
            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery("match (n) return count(n) as countOfNodes")) {
                if(resultSet.next()) {
                    return resultSet.getObject("countOfNodes");
                }
            }
        }

Above mentioned code is coupled with following code:

    protected Connection neoConnection() throws SQLException {
        return DriverManager.getConnection("jdbc:neo4j:bolt://localhost:7687", "username","password");
    }

This code works for few iterations, but after a while starts giving error as mentioned below:

java.sql.SQLException: org.neo4j.driver.v1.exceptions.ClientException: Failed to establish connection with server. Make sure that you have a server with bolt enabled on localhost:7687
	at org.neo4j.jdbc.bolt.BoltDriver.connect(BoltDriver.java:67)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
Caused by: org.neo4j.driver.v1.exceptions.ClientException: Failed to establish connection with server. Make sure that you have a server with bolt enabled on localhost:7687
	at org.neo4j.driver.internal.connector.socket.SocketClient.negotiateProtocol(SocketClient.java:195)
	at org.neo4j.driver.internal.connector.socket.SocketClient.start(SocketClient.java:76)
	at org.neo4j.driver.internal.connector.socket.SocketConnection.<init>(SocketConnection.java:64)
	at org.neo4j.driver.internal.connector.socket.SocketConnector.connect(SocketConnector.java:52)
	at org.neo4j.driver.internal.pool.InternalConnectionPool.acquire(InternalConnectionPool.java:113)
	at org.neo4j.driver.internal.InternalDriver.session(InternalDriver.java:53)
	at org.neo4j.jdbc.bolt.BoltDriver.connect(BoltDriver.java:63)
	... 115 more

PS: Just want to add one more point over here. This works with HTTP JDBC driver and this issue is faced only when used with Bolt JDBC

**Comment by inserpio** [comment]
Hi @AbhayParab, I just implemented the following test:

```
@Test
public void issue94() {

   for (int i = 0; i < 1000; i++) {
      try (Connection connection = neoConnection()) {
         try (Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("match (n) return count(n) as countOfNodes")) {
            if(resultSet.next()) {
               resultSet.getObject("countOfNodes");
            }
         }
      }
      catch (Exception e) {
         Assert.fail(e.getMessage());
      }
   }
}

protected Connection neoConnection() throws SQLException {
   return DriverManager.getConnection("jdbc:neo4j:bolt://localhost?noSsl", "neo4j", "larus");
}
```

But this didn't help me to replicate the problem and understand the cause.
I'll keep investigating but it looks like something is exhausting some resource.
Could you please send me the complete code or at least give me some more context?

Thank you very much,
Lorenzo

**Comment by inserpio** [comment]
@AbhayParab which neo4j version are you using?

**Comment by AbhayParab** [comment]
@inserpio I am using neo4j 3.1.1

Also I have reproduced the issue. When i loop for 1000, test code that you had shared works as expected. However if i increase loop to 10000, it started giving me same error that i was receiving earlier.

Hence for finding out the fail-over point, i have started reducing number of executions. Listed below is synopsis my test

1. 1000 -> Success
2. 10000 -> Faillure
3. 5000 -> Failure
4. 3000 -> Failure
5. 1500 -> Success
6. 2200 -> Failure
7. 1900 -> Failure. But error was different [java.sql.SQLException: org.neo4j.driver.v1.exceptions.ClientException: Unable to process request: Address already in use]
8. 1700 -> Success

When i had executed similar test multiple times, i am getting such error at different number of iterations. 

PS: Wanted to update about some observations that I had
1. When observing java process of neo4j server in activity monitor, i can see multiple numbers of ports being opened. Number of ports being opened is related to number of iterations but not 1-to-1. Its approx twice the number of iterations
2. When whole program is successful, no of ports gets reduced to around 150 usually. However when program fails, ports are not released. (same is case with threads running). 
3. General observations : When program fails, no of ports is more than 2K 
 & no of threads more than 1K)

Hope this is helpful in identification of issue.

**Comment by inserpio** [comment]
Hi @AbhayParab, many thanks for this addition information. They are for sure very useful in order to better identify the root cause for this issue.
I really looks like a resource leak, i.e. too many sockets.
If you try to save the opened connection in a variable instead of asking for a new one every iteration (calling `DriverManager.getConnection`) everything start working again.
Let me check where things remain allocated and I'll ping you back asap.
Thanks again.
Lorenzo

**Comment by AbhayParab** [comment]
@inserpio Thanks for confirmation.

Regarding opening connection once and using it across, i do agree that it does work (verified the same as well). However that goes against the typical JDBC usage perspective (since such usage would cause memory leaks and invalid exception handling). Hence i am not much inclined for going by that way. Hence as short term measure, i am using HTTP JDBC driver.

Thanks for you help

**Comment by inserpio** [comment]
@glaggia-larus could you please create an integration test for this issue (it should be already solved but IMHO it deserves a test to cover it).
